class ExportCardConfiguration < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[ExportCardConfiguration, ActiveRecord_Relation, Integer]

  module GeneratedAttributeMethods
    def id: () -> Integer

    def id=: (Integer) -> Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ Integer?, Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> Array[Integer?]?

    def id_previously_was: () -> Integer?

    def id_before_last_save: () -> Integer?

    def id_change_to_be_saved: () -> Array[Integer?]?

    def id_in_database: () -> Integer?

    def saved_change_to_id: () -> Array[Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def name: () -> String?

    def name=: (String?) -> String?

    def name?: () -> bool

    def name_changed?: () -> bool

    def name_change: () -> [ String?, String? ]

    def name_will_change!: () -> void

    def name_was: () -> String?

    def name_previously_changed?: () -> bool

    def name_previous_change: () -> Array[String?]?

    def name_previously_was: () -> String?

    def name_before_last_save: () -> String?

    def name_change_to_be_saved: () -> Array[String?]?

    def name_in_database: () -> String?

    def saved_change_to_name: () -> Array[String?]?

    def saved_change_to_name?: () -> bool

    def will_save_change_to_name?: () -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def per_page: () -> Integer?

    def per_page=: (Integer?) -> Integer?

    def per_page?: () -> bool

    def per_page_changed?: () -> bool

    def per_page_change: () -> [ Integer?, Integer? ]

    def per_page_will_change!: () -> void

    def per_page_was: () -> Integer?

    def per_page_previously_changed?: () -> bool

    def per_page_previous_change: () -> Array[Integer?]?

    def per_page_previously_was: () -> Integer?

    def per_page_before_last_save: () -> Integer?

    def per_page_change_to_be_saved: () -> Array[Integer?]?

    def per_page_in_database: () -> Integer?

    def saved_change_to_per_page: () -> Array[Integer?]?

    def saved_change_to_per_page?: () -> bool

    def will_save_change_to_per_page?: () -> bool

    def restore_per_page!: () -> void

    def clear_per_page_change: () -> void

    def page_size: () -> String?

    def page_size=: (String?) -> String?

    def page_size?: () -> bool

    def page_size_changed?: () -> bool

    def page_size_change: () -> [ String?, String? ]

    def page_size_will_change!: () -> void

    def page_size_was: () -> String?

    def page_size_previously_changed?: () -> bool

    def page_size_previous_change: () -> Array[String?]?

    def page_size_previously_was: () -> String?

    def page_size_before_last_save: () -> String?

    def page_size_change_to_be_saved: () -> Array[String?]?

    def page_size_in_database: () -> String?

    def saved_change_to_page_size: () -> Array[String?]?

    def saved_change_to_page_size?: () -> bool

    def will_save_change_to_page_size?: () -> bool

    def restore_page_size!: () -> void

    def clear_page_size_change: () -> void

    def orientation: () -> String?

    def orientation=: (String?) -> String?

    def orientation?: () -> bool

    def orientation_changed?: () -> bool

    def orientation_change: () -> [ String?, String? ]

    def orientation_will_change!: () -> void

    def orientation_was: () -> String?

    def orientation_previously_changed?: () -> bool

    def orientation_previous_change: () -> Array[String?]?

    def orientation_previously_was: () -> String?

    def orientation_before_last_save: () -> String?

    def orientation_change_to_be_saved: () -> Array[String?]?

    def orientation_in_database: () -> String?

    def saved_change_to_orientation: () -> Array[String?]?

    def saved_change_to_orientation?: () -> bool

    def will_save_change_to_orientation?: () -> bool

    def restore_orientation!: () -> void

    def clear_orientation_change: () -> void

    def rows: () -> String?

    def rows=: (String?) -> String?

    def rows?: () -> bool

    def rows_changed?: () -> bool

    def rows_change: () -> [ String?, String? ]

    def rows_will_change!: () -> void

    def rows_was: () -> String?

    def rows_previously_changed?: () -> bool

    def rows_previous_change: () -> Array[String?]?

    def rows_previously_was: () -> String?

    def rows_before_last_save: () -> String?

    def rows_change_to_be_saved: () -> Array[String?]?

    def rows_in_database: () -> String?

    def saved_change_to_rows: () -> Array[String?]?

    def saved_change_to_rows?: () -> bool

    def will_save_change_to_rows?: () -> bool

    def restore_rows!: () -> void

    def clear_rows_change: () -> void

    def active: () -> bool?

    def active=: (bool?) -> bool?

    def active?: () -> bool

    def active_changed?: () -> bool

    def active_change: () -> [ bool?, bool? ]

    def active_will_change!: () -> void

    def active_was: () -> bool?

    def active_previously_changed?: () -> bool

    def active_previous_change: () -> Array[bool?]?

    def active_previously_was: () -> bool?

    def active_before_last_save: () -> bool?

    def active_change_to_be_saved: () -> Array[bool?]?

    def active_in_database: () -> bool?

    def saved_change_to_active: () -> Array[bool?]?

    def saved_change_to_active?: () -> bool

    def will_save_change_to_active?: () -> bool

    def restore_active!: () -> void

    def clear_active_change: () -> void

    def description: () -> String?

    def description=: (String?) -> String?

    def description?: () -> bool

    def description_changed?: () -> bool

    def description_change: () -> [ String?, String? ]

    def description_will_change!: () -> void

    def description_was: () -> String?

    def description_previously_changed?: () -> bool

    def description_previous_change: () -> Array[String?]?

    def description_previously_was: () -> String?

    def description_before_last_save: () -> String?

    def description_change_to_be_saved: () -> Array[String?]?

    def description_in_database: () -> String?

    def saved_change_to_description: () -> Array[String?]?

    def saved_change_to_description?: () -> bool

    def will_save_change_to_description?: () -> bool

    def restore_description!: () -> void

    def clear_description_change: () -> void
  end
  include GeneratedAttributeMethods

  module GeneratedAssociationMethods
  end
  include GeneratedAssociationMethods

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[ExportCardConfiguration, Integer]
    include Enumerable[ExportCardConfiguration]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[ExportCardConfiguration, Integer]
  end
end
