class OAuthClient < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[OAuthClient, ActiveRecord_Relation, Integer]

  module GeneratedAttributeMethods
    def id: () -> Integer

    def id=: (Integer) -> Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ Integer?, Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> Array[Integer?]?

    def id_previously_was: () -> Integer?

    def id_before_last_save: () -> Integer?

    def id_change_to_be_saved: () -> Array[Integer?]?

    def id_in_database: () -> Integer?

    def saved_change_to_id: () -> Array[Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def client_id: () -> String

    def client_id=: (String) -> String

    def client_id?: () -> bool

    def client_id_changed?: () -> bool

    def client_id_change: () -> [ String?, String? ]

    def client_id_will_change!: () -> void

    def client_id_was: () -> String?

    def client_id_previously_changed?: () -> bool

    def client_id_previous_change: () -> Array[String?]?

    def client_id_previously_was: () -> String?

    def client_id_before_last_save: () -> String?

    def client_id_change_to_be_saved: () -> Array[String?]?

    def client_id_in_database: () -> String?

    def saved_change_to_client_id: () -> Array[String?]?

    def saved_change_to_client_id?: () -> bool

    def will_save_change_to_client_id?: () -> bool

    def restore_client_id!: () -> void

    def clear_client_id_change: () -> void

    def client_secret: () -> String

    def client_secret=: (String) -> String

    def client_secret?: () -> bool

    def client_secret_changed?: () -> bool

    def client_secret_change: () -> [ String?, String? ]

    def client_secret_will_change!: () -> void

    def client_secret_was: () -> String?

    def client_secret_previously_changed?: () -> bool

    def client_secret_previous_change: () -> Array[String?]?

    def client_secret_previously_was: () -> String?

    def client_secret_before_last_save: () -> String?

    def client_secret_change_to_be_saved: () -> Array[String?]?

    def client_secret_in_database: () -> String?

    def saved_change_to_client_secret: () -> Array[String?]?

    def saved_change_to_client_secret?: () -> bool

    def will_save_change_to_client_secret?: () -> bool

    def restore_client_secret!: () -> void

    def clear_client_secret_change: () -> void

    def integration_type: () -> String

    def integration_type=: (String) -> String

    def integration_type?: () -> bool

    def integration_type_changed?: () -> bool

    def integration_type_change: () -> [ String?, String? ]

    def integration_type_will_change!: () -> void

    def integration_type_was: () -> String?

    def integration_type_previously_changed?: () -> bool

    def integration_type_previous_change: () -> Array[String?]?

    def integration_type_previously_was: () -> String?

    def integration_type_before_last_save: () -> String?

    def integration_type_change_to_be_saved: () -> Array[String?]?

    def integration_type_in_database: () -> String?

    def saved_change_to_integration_type: () -> Array[String?]?

    def saved_change_to_integration_type?: () -> bool

    def will_save_change_to_integration_type?: () -> bool

    def restore_integration_type!: () -> void

    def clear_integration_type_change: () -> void

    def integration_id: () -> Integer

    def integration_id=: (Integer) -> Integer

    def integration_id?: () -> bool

    def integration_id_changed?: () -> bool

    def integration_id_change: () -> [ Integer?, Integer? ]

    def integration_id_will_change!: () -> void

    def integration_id_was: () -> Integer?

    def integration_id_previously_changed?: () -> bool

    def integration_id_previous_change: () -> Array[Integer?]?

    def integration_id_previously_was: () -> Integer?

    def integration_id_before_last_save: () -> Integer?

    def integration_id_change_to_be_saved: () -> Array[Integer?]?

    def integration_id_in_database: () -> Integer?

    def saved_change_to_integration_id: () -> Array[Integer?]?

    def saved_change_to_integration_id?: () -> bool

    def will_save_change_to_integration_id?: () -> bool

    def restore_integration_id!: () -> void

    def clear_integration_id_change: () -> void

    def created_at: () -> ActiveSupport::TimeWithZone

    def created_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: () -> bool

    def created_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: () -> bool

    def created_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> Array[ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def updated_at: () -> ActiveSupport::TimeWithZone

    def updated_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: () -> bool

    def updated_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: () -> bool

    def updated_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> Array[ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void
  end
  include GeneratedAttributeMethods

  def integration: () -> untyped
  def integration=: (untyped?) -> untyped?
  def reload_integration: () -> untyped?
  module GeneratedAssociationMethods
  end
  include GeneratedAssociationMethods

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[OAuthClient, Integer]
    include Enumerable[OAuthClient]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[OAuthClient, Integer]
  end
end
