module ActiveJob
  class Base
    extend ActiveJob::Callbacks::ClassMethods
    extend ActiveJob::Core::ClassMethods
    extend ActiveJob::Enqueuing::ClassMethods
    extend ActiveJob::Exceptions::ClassMethods
    extend ActiveJob::Execution::ClassMethods
    extend ActiveJob::QueueAdapter::ClassMethods
    extend ActiveJob::QueueName::ClassMethods
    extend ActiveJob::QueuePriority::ClassMethods

    def self.queue_as: (*untyped) -> void | ...
    def self.queue_with_priority: (?untyped? priority) -> void | ...
    def self.before_perform: (*untyped filters) -> void | ...
    def self.after_perform: (*untyped filters) -> void | ...
    def self.around_perform: (*untyped filters) -> void | ...
    def self.before_enqueue: (*untyped filters) -> void | ...
    def self.after_enqueue: (*untyped filters) -> void | ...
    def self.around_enqueue: (*untyped filters) -> void | ...
    def self.retry_on: (*untyped) -> void | ...
    def self.discard_on: (*untyped) -> void | ...
  end
end
