class ParseSchemaFilterParamsService
  extend ActiveModel::Naming

  extend ActiveModel::Translation

  attr_accessor user: untyped

  def self.i18n_scope: () -> :activerecord

  def initialize: (user: untyped) -> void

  def call: (untyped filter) -> untyped

  private

  def check_error_in_filter: (untyped filter) -> (:id_filter_required | :unsupported_operator | :invalid_values | nil)

  def parse_ids: (untyped filter) -> untyped

  def error: (untyped message) -> untyped

  def success: (untyped result) -> untyped

  def valid_project_type_pairs: (untyped filter) -> untyped

  def projects_by_id: (untyped ids) -> untyped

  def types_by_id: (untyped ids) -> untyped

  def only_valid_pairs: (untyped id_pairs, untyped projects_map, untyped types_map) -> untyped

  def string_pairs_to_object_pairs: (untyped string_pairs, untyped projects_map, untyped types_map) -> untyped
end
