module OpenProject::TextFormatting
  module Filters
    class PlainFilter < HTML::Pipeline::TextFilter
      include ERB::Util

      include ActionView::Helpers::TagHelper

      include ActionView::Helpers::TextHelper

      include ActionView::Helpers::UrlHelper

      def call: () -> untyped
    end
  end
end
