module BudgetsHelper
  include ActionView::Helpers::NumberHelper

  include Redmine::I18n

  # Check if the current user is allowed to manage the budget.  Based on Role
  # permissions.
  def allowed_management?: () -> untyped

  def budgets_to_csv: (untyped budgets) -> untyped

  def budget_attachment_representer: (untyped message) -> untyped
end
