module Calendar
  class RowComponent < ::RowComponent
    def query: () -> untyped

    def name: () -> untyped

    def created_at: () -> untyped

    def button_links: () -> untyped

    def delete_link: () -> (untyped | nil)
  end
end
