#-- encoding: UTF-8
#-- copyright
# ChiliProject is a project management system.
#
# Copyright (C) 2010-2011 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

desc 'Generates a configuration file for cookie store sessions.'

file 'config/initializers/secret_token.rb' do
  path = Rails.root.join('config/initializers/secret_token.rb').to_s
  secret = SecureRandom.hex(128)
  File.open(path, 'w') do |f|
    f.write <<"EOF"
# This file was generated by 'rake config/initializers/secret_token.rb',
# and should not be made visible to public.
# If you have a load-balancing OpenProject cluster, you will need to use the
# same version of this file on each machine. And be sure to restart your
# server when you modify this file.

# Your secret key for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
OpenProject::Application.config.secret_token = '#{secret}'
EOF
  end
end

desc 'Generates a configuration file for cookie store sessions.'
task :generate_secret_token => ['config/initializers/secret_token.rb']
