module Queries
  module Relations
    module Filters
      class ToFilter < ::Queries::Relations::Filters::RelationFilter
        include ::Queries::Relations::Filters::VisibilityChecking

        def type: () -> :integer

        def self.key: () -> :to_id

        def visibility_checked?: () -> true

        private

        def visibility_checked_sql: (untyped operator, untyped values, untyped visible_sql) -> ::Array[::String | untyped]
      end
    end
  end
end
