class Queries::WorkPackages::Filter::BlocksFilter < Queries::WorkPackages::Filter::WorkPackageFilter
  include ::Queries::WorkPackages::Filter::FilterOnDirectedRelationsMixin

  def relation_type: () -> untyped

  private

  def relation_filter: () -> { to_id: untyped }

  def relation_select: () -> :from_id
end
