class Queries::WorkPackages::Filter::DuplicatedFilter < Queries::WorkPackages::Filter::WorkPackageFilter
  include ::Queries::WorkPackages::Filter::FilterOnDirectedRelationsMixin

  def relation_type: () -> untyped

  private

  def relation_filter: () -> { from_id: untyped }

  def relation_select: () -> :to_id
end
