module Queries::WorkPackages::Filter::FilterOnUndirectedRelationsMixin
  include ::Queries::WorkPackages::Filter::FilterForWpMixin

  def where: () -> ::String

  def relation_type: () -> untyped

  private

  def operator_and_junction: () -> (::Array["IN" | "OR"] | ::Array["NOT IN" | "AND"])

  def relations_subselect_to_from: () -> untyped

  def relations_subselect_from_to: () -> untyped

  def relation_subselect: () -> untyped
end
