#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# See COPYRIGHT and LICENSE files for more details.
#++

services:
  traefik:
    environment:
      # For step CA only: Overwrite trusted CA certificates with Step root CA (not needed for Let's encrypt)
      LEGO_CA_CERTIFICATES: /step/certs/root_ca.crt
      # Overwrite to enable Let's encrypt instead of using Step CA for certificate generation
      # TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_CERTRESOLVER: letsencrypt
      # TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: you@example.com

    # Necessary for certificates via Step CA only
    depends_on:
      step:
        condition: service_healthy

    # Enabling traefik for the traefik container itself will give you access to the Traefik Dashboard, which can be a useful
    # tool to inspect whether everything is working fine. It's not advised to publicly expose this dashboard.
    labels:
      - "traefik.enable=true"
