#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# See COPYRIGHT and LICENSE files for more details.
#++

services:
  db-keycloak:
    image: postgres:17
    restart: unless-stopped
    networks:
      - external
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.6
    command:
    - "start-dev"
    - "--proxy-headers"
    - "xforwarded"
    - "--spi-connections-http-client-default-disable-trust-manager=true"
    # Uncomment the lines below to make changes to the Keycloak theme, this will ensure that changes become immediately visible.
    # - "--spi-theme-static-max-age=-1"
    # - "--spi-theme-cache-themes=false"
    # - "--spi-theme-cache-templates=false"
    restart: unless-stopped
    networks:
      - external
    extra_hosts:
      - "openproject.local:host-gateway"
    environment:
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_DB_URL=jdbc:postgresql://db-keycloak:5432/keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_SCHEMA=public
      - KC_HOSTNAME=keycloak.${OPENPROJECT_DOCKER_DEV_TLD:-local}
      - KC_TRANSACTION_XA_ENABLED=false
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - keycloak-data:/opt/keycloak/data/
      - ./themes/:/opt/keycloak/themes/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak-sub-secure.rule=Host(`keycloak.${OPENPROJECT_DOCKER_DEV_TLD:-local}`)"
      - "traefik.http.routers.keycloak-sub-secure.entrypoints=websecure"
    depends_on:
      - db-keycloak

volumes:
  keycloak-data:
  pgdata:

networks:
  external:
    name: gateway
    external: true
