module Bim::Bcf::API::V2_1::Viewpoints
  class FullRepresenter < BaseRepresenter
    def self.selector: () -> "json_viewpoint - 'components' as json_viewpoint"

    def scope: () -> untyped
  end
end
