user: openproject
group: openproject
targets:
  debian-7: &debian
    build_dependencies:
      - libmagickwand-dev
      - libsqlite3-dev
  debian-8:
    <<: *debian
  ubuntu-14.04:
    <<: *debian
  fedora-20: &redhat
    build_dependencies:
      - ImageMagick-devel
  centos-6:
    <<: *redhat
  centos-7:
    <<: *redhat
    dependencies:
      - epel-release
  sles-12:
    build_dependencies:
      - ImageMagick-devel
before_precompile: "packaging/setup"
crons:
  - packaging/cron/openproject-clear-old-sessions
  - packaging/cron/openproject-create-svn-repositories
services:
  - postgres
installer: https://github.com/pkgr/installer.git
wizards:
  - https://github.com/pkgr/addon-legacy-installer.git
  - https://github.com/pkgr/addon-mysql.git
  - https://github.com/pkgr/addon-apache2.git
  - https://github.com/pkgr/addon-svn-dav.git
  - https://github.com/pkgr/addon-smtp.git
  - https://github.com/pkgr/addon-memcached.git
  - https://github.com/pkgr/addon-openproject.git
buildpack: https://github.com/ddollar/heroku-buildpack-multi.git
