user: openproject
group: openproject
description: OpenProject
homepage: "https://www.openproject.org"
maintainer: "operations+packaging@openproject.com"
license: "GPL"
targets:
  debian-9: &debian9
    build_dependencies:
      - libsqlite3-dev
    dependencies:
      - unzip
      - poppler-utils
      - unrtf
      - tesseract-ocr
      - catdoc
      - imagemagick
  debian-10:
    <<: *debian9
  debian-11:
    <<: *debian9
  ubuntu-16.04:
    <<: *debian9
  ubuntu-18.04:
    <<: *debian9
  ubuntu-20.04:
    <<: *debian9
  centos-7: &centos7
    dependencies:
      - epel-release
      - ImageMagick
      - unzip
      - poppler-utils
  centos-8:
    <<: *centos7
  sles-12:
    build_dependencies:
      - sqlite3-devel
      - ImageMagick
before_precompile: "packaging/setup"
after_precompile: "packaging/teardown"
services:
  - postgres
installer: https://github.com/pkgr/installer.git
wizards:
  - https://github.com/pkgr/addon-legacy-installer.git
  - ./packaging/addons/openproject-edition
  - https://github.com/pkgr/addon-postgres
  - https://github.com/pkgr/addon-apache2.git
  - ./packaging/addons/repositories
  - https://github.com/pkgr/addon-smtp.git
  - https://github.com/pkgr/addon-memcached.git
  - ./packaging/addons/openproject
buildpack: https://github.com/opf/heroku-buildpack-multi.git#master
env:
  - NODE_ENV=production
  - NPM_CONFIG_PRODUCTION=false
