project:
  after:
    - npm install npm
stage:
  before:
    - pushd frontend;
      npm install --unsafe-perm --ignore-scripts;
      bower install --allow-root;
      popd
    - cp config/configuration.yml.example config/configuration.yml
    - cp config/database.teatro.yml config/database.yml
    - bundle exec rake generate_secret_token

  database:
    - bundle exec rake db:create db:migrate
    - bundle exec rake db:seed RAILS_ENV=development

  assets: bundle exec rake assets:webpack RAILS_ENV=development
  run: foreman start -f Procfile.dev -c all=1,assets=0
