cp /media/sf_GitHub/openproject/app/cells/projects/table_cell.rb ./openproject/app/cells/projects/table_cell.rb
cp /media/sf_GitHub/openproject/app/controllers/attribute_help_texts_controller.rb ./openproject/app/controllers/attribute_help_texts_controller.rb
cp /media/sf_GitHub/openproject/app/controllers/custom_actions_controller.rb ./openproject/app/controllers/custom_actions_controller.rb
cp /media/sf_GitHub/openproject/app/controllers/custom_fields_controller.rb ./openproject/app/controllers/custom_fields_controller.rb
cp /media/sf_GitHub/openproject/app/controllers/custom_styles_controller.rb ./openproject/app/controllers/custom_styles_controller.rb
cp /media/sf_GitHub/openproject/app/controllers/members_controller.rb ./openproject/app/controllers/members_controller.rb
cp /media/sf_GitHub/openproject/app/controllers/users_controller.rb ./openproject/app/controllers/users_controller.rb
cp /media/sf_GitHub/openproject/app/helpers/application_helper.rb ./openproject/app/helpers/application_helper.rb
cp /media/sf_GitHub/openproject/app/helpers/homescreen_helper.rb ./openproject/app/helpers/homescreen_helper.rb
cp /media/sf_GitHub/openproject/app/helpers/projects_helper.rb ./openproject/app/helpers/projects_helper.rb
cp /media/sf_GitHub/openproject/app/helpers/search_helper.rb ./openproject/app/helpers/search_helper.rb
cp /media/sf_GitHub/openproject/app/helpers/security_badge_helper.rb ./openproject/app/helpers/security_badge_helper.rb
cp /media/sf_GitHub/openproject/app/models/setting.rb ./openproject/app/models/setting.rb
cp /media/sf_GitHub/openproject/app/models/status.rb ./openproject/app/models/status.rb
cp /media/sf_GitHub/openproject/app/models/user.rb ./openproject/app/models/user.rb
cp /media/sf_GitHub/openproject/app/models/queries/work_packages/columns/relation_column.rb ./openproject/app/models/queries/work_packages/columns/relation_column.rb
cp /media/sf_GitHub/openproject/app/models/queries/work_packages/columns/relation_of_type_column.rb ./openproject/app/models/queries/work_packages/columns/relation_of_type_column.rb
cp /media/sf_GitHub/openproject/app/models/queries/work_packages/columns/relation_to_type_column.rb ./openproject/app/models/queries/work_packages/columns/relation_to_type_column.rb
cp /media/sf_GitHub/openproject/app/models/queries/work_packages/filter/attachment_base_filter.rb ./openproject/app/models/queries/work_packages/filter/attachment_base_filter.rb
cp /media/sf_GitHub/openproject/app/models/queries/work_packages/filter/search_filter.rb ./openproject/app/models/queries/work_packages/filter/search_filter.rb
cp /media/sf_GitHub/openproject/app/models/query/highlighting.rb ./openproject/app/models/query/highlighting.rb
cp /media/sf_GitHub/openproject/app/models/work_packages/scopes/for_scheduling.rb ./openproject/app/models/work_packages/scopes/for_scheduling.rb
cp /media/sf_GitHub/openproject/app/services/authorization/enterprise_service.rb ./openproject/app/services/authorization/enterprise_service.rb
cp /media/sf_GitHub/openproject/app/services/users/register_user_service.rb ./openproject/app/services/users/register_user_service.rb
cp /media/sf_GitHub/openproject/app/views/common/_favicons.html.erb ./openproject/app/views/common/_favicons.html.erb
cp /media/sf_GitHub/openproject/app/views/custom_fields/_form.html.erb ./openproject/app/views/custom_fields/_form.html.erb
cp /media/sf_GitHub/openproject/app/views/custom_styles/_inline_css_logo.erb ./openproject/app/views/custom_styles/_inline_css_logo.erb
cp /media/sf_GitHub/openproject/app/views/layouts/base.html.erb ./openproject/app/views/layouts/base.html.erb
cp /media/sf_GitHub/openproject/app/views/ldap_auth_sources/_form.html.erb ./openproject/app/views/ldap_auth_sources/_form.html.erb
cp /media/sf_GitHub/openproject/app/views/members/_member_form.html.erb ./openproject/app/views/members/_member_form.html.erb
cp /media/sf_GitHub/openproject/app/views/projects/filters/_form.html.erb ./openproject/app/views/projects/filters/_form.html.erb
cp /media/sf_GitHub/openproject/app/views/statuses/_form.html.erb ./openproject/app/views/statuses/_form.html.erb
cp /media/sf_GitHub/openproject/app/views/types/form/_form_configuration.html.erb ./openproject/app/views/types/form/_form_configuration.html.erb
cp /media/sf_GitHub/openproject/app/views/users/index.html.erb ./openproject/app/views/users/index.html.erb
cp /media/sf_GitHub/openproject/app/views/work_packages/settings/work_package_tracking.html.erb ./openproject/app/views/work_packages/settings/work_package_tracking.html.erb
cp /media/sf_GitHub/openproject/lib/open_project/configuration.rb ./openproject/lib/open_project/configuration.rb
cp /media/sf_GitHub/openproject/lib/open_project/version.rb ./openproject/lib/open_project/version.rb
cp /media/sf_GitHub/openproject/lib/open_project/configuration/helpers.rb ./openproject/lib/open_project/configuration/helpers.rb
cp /media/sf_GitHub/openproject/lib/plugins/acts_as_searchable/lib/acts_as_searchable.rb ./openproject/lib/plugins/acts_as_searchable/lib/acts_as_searchable.rb
cp /media/sf_GitHub/openproject/lib/redmine/menu_manager/top_menu/help_menu.rb ./openproject/lib/redmine/menu_manager/top_menu/help_menu.rb
cp /media/sf_GitHub/openproject/modules/auth_plugins/lib/open_project/plugins/auth_plugin.rb ./openproject/modules/auth_plugins/lib/open_project/plugins/auth_plugin.rb
cp /media/sf_GitHub/openproject/modules/grids/lib/grids/configuration/in_project_base_registration.rb ./openproject/modules/grids/lib/grids/configuration/in_project_base_registration.rb
cp /media/sf_GitHub/openproject/modules/ldap_groups/app/controllers/ldap_groups/synchronized_filters_controller.rb ./openproject/modules/ldap_groups/app/controllers/ldap_groups/synchronized_filters_controller.rb
cp /media/sf_GitHub/openproject/modules/ldap_groups/app/controllers/ldap_groups/synchronized_groups_controller.rb ./openproject/modules/ldap_groups/app/controllers/ldap_groups/synchronized_groups_controller.rb
cp /media/sf_GitHub/openproject/modules/ldap_groups/app/workers/ldap_groups/synchronization_job.rb ./openproject/modules/ldap_groups/app/workers/ldap_groups/synchronization_job.rb
cp /media/sf_GitHub/openproject/modules/openid_connect/app/controllers/openid_connect/providers_controller.rb ./openproject/modules/openid_connect/app/controllers/openid_connect/providers_controller.rb
cp /media/sf_GitHub/openproject/modules/two_factor_authentication/app/controllers/two_factor_authentication/two_factor_settings_controller.rb ./openproject/modules/two_factor_authentication/app/controllers/two_factor_authentication/two_factor_settings_controller.rb
cp /media/sf_GitHub/openproject/modules/two_factor_authentication/lib/open_project/two_factor_authentication/token_strategy_manager.rb ./openproject/modules/two_factor_authentication/lib/open_project/two_factor_authentication/token_strategy_manager.rb
