//-- copyright
// OpenProject is an open source project management software.
// Copyright (C) the OpenProject GmbH
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License version 3.
//
// OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
// Copyright (C) 2006-2013 Jean-Philippe Lang
// Copyright (C) 2010-2013 the ChiliProject Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
//
// See COPYRIGHT and LICENSE files for more details.
//++

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { OpIconComponent } from './icon.component';
import {
  ChevronLeftIconComponent,
  ChevronRightIconComponent,
  ClockIconComponent,
  HomeIconComponent,
  InfoIconComponent,
  OpAlarmIconComponent,
  OpAlarmSetIconComponent,
  OpCursorRectangleSelectIconComponent,
  OpCursorSelectIconComponent,
  OpEnterpriseAddonsIconComponent,
  OpEraseIconComponent,
  OpFirstPersonViewIconComponent,
  OpGridMenuIconComponent,
  OpGroupIconComponent,
  OpHierarchyIconComponent,
  OpNoHierarchyIconComponent,
  OpOrthographicPerspectiveIconComponent,
  OpResizerVerticalLinesIconComponent,
  OpScissorsIconComponent,
  OpThreedReturnDefaultIconComponent,
  OpViewFitToIconComponent,
  OpViewModalIconComponent,
  OpViewThreedIconComponent,
  PackageIconComponent,
  PersonIconComponent,
  QuestionIconComponent,
  ScreenFullIconComponent,
  ShareAndroidIconComponent,
  StarFillIconComponent,
  StarIconComponent,
  XIconComponent,
  OpGitlabIssueClosedIconComponent,
  OpGitlabLabelsIconComponent,
  OpGitlabIssueOpenIconComponent,
  OpGitlabMergeRequestClosedIconComponent,
  OpGitlabMergeRequestMergedIconComponent,
  OpGitlabMergeRequestOpenIconComponent,
  OpGitlabMergeRequestReadyIconComponent,
  OpGitlabPipelineStatusCanceledIconComponent,
  OpGitlabPipelineStatusCreatedIconComponent,
  OpGitlabPipelineStatusFailedIconComponent,
  OpGitlabPipelineStatusManualIconComponent,
  OpGitlabPipelineStatusPendingIconComponent,
  OpGitlabPipelineStatusPreparingIconComponent,
  OpGitlabPipelineStatusRunningIconComponent,
  OpGitlabPipelineStatusScheduledIconComponent,
  OpGitlabPipelineStatusSkippedIconComponent,
  OpGitlabPipelineStatusSuccessIconComponent,
  OpGitlabPipelineStatusWaitingIconComponent,
  XCircleIconComponent,
  KebabHorizontalIconComponent,
  ReadIconComponent,
  EyeIconComponent,
  EyeClosedIconComponent,
  ArrowLeftIconComponent,
  GrabberIconComponent,
  PlusIconComponent,
  OpFileCsvIconComponent,
  OpFileDocIconComponent,
  OpFileSheetIconComponent,
  OpFileTextIconComponent,
  OpFilePresentationIconComponent,
  OpPdfIconComponent,
  CloudIconComponent,
  DownloadIconComponent,
  FileDirectoryFillIconComponent,
  FileDirectoryOpenFillIconComponent,
  ServerIconComponent,
  FileIconComponent,
  FileMediaIconComponent,
  TasklistIconComponent,
  LinkIconComponent,
  LinkExternalIconComponent,
  UploadIconComponent,
  UnlinkIconComponent,
  OpMarkNextcloudIconComponent,
  AlertFillIconComponent,
  BugIconComponent,
  TrashIconComponent,
  PaperclipIconComponent,
  OpAddAttachmentIconComponent,
  TriangleRightIconComponent,
  OpStopwatchStopIconComponent,
  CopyIconComponent,
  TriangleDownIconComponent,
  OpArrowInIconComponent,
  ReplyIconComponent,
  OpTriangleDeltaIconComponent,
  OpBaselineIconComponent,
  SearchIconComponent,
  AlertIconComponent,
  ListUnorderedIconComponent,
  OpStopwatchStartIconComponent,
  ChevronDownIconComponent,
  VersionsIconComponent,
  BriefcaseIconComponent,
  CircleSlashIconComponent
} from '@openproject/octicons-angular';

@NgModule({
  imports: [
    CommonModule,

    AlertIconComponent,
    AlertFillIconComponent,
    BugIconComponent,
    ChevronDownIconComponent,
    ChevronLeftIconComponent,
    ChevronRightIconComponent,
    ClockIconComponent,
    CloudIconComponent,
    CopyIconComponent,
    DownloadIconComponent,
    FileDirectoryFillIconComponent,
    FileDirectoryOpenFillIconComponent,
    FileIconComponent,
    FileMediaIconComponent,
    HomeIconComponent,
    InfoIconComponent,
    LinkIconComponent,
    LinkExternalIconComponent,
    ListUnorderedIconComponent,
    OpAddAttachmentIconComponent,
    OpAlarmIconComponent,
    OpAlarmSetIconComponent,
    OpArrowInIconComponent,
    OpBaselineIconComponent,
    OpCursorRectangleSelectIconComponent,
    OpCursorSelectIconComponent,
    OpEnterpriseAddonsIconComponent,
    OpEraseIconComponent,
    OpFileCsvIconComponent,
    OpFileDocIconComponent,
    OpFilePresentationIconComponent,
    OpFileSheetIconComponent,
    OpFileTextIconComponent,
    OpFirstPersonViewIconComponent,
    OpGridMenuIconComponent,
    OpGroupIconComponent,
    OpHierarchyIconComponent,
    OpNoHierarchyIconComponent,
    OpMarkNextcloudIconComponent,
    OpOrthographicPerspectiveIconComponent,
    OpPdfIconComponent,
    OpResizerVerticalLinesIconComponent,
    OpScissorsIconComponent,
    OpStopwatchStartIconComponent,
    OpStopwatchStopIconComponent,
    OpThreedReturnDefaultIconComponent,
    OpTriangleDeltaIconComponent,
    OpViewFitToIconComponent,
    OpViewModalIconComponent,
    OpViewThreedIconComponent,
    PackageIconComponent,
    PaperclipIconComponent,
    PersonIconComponent,
    QuestionIconComponent,
    ScreenFullIconComponent,
    SearchIconComponent,
    ServerIconComponent,
    ShareAndroidIconComponent,
    StarFillIconComponent,
    StarIconComponent,
    TasklistIconComponent,
    TrashIconComponent,
    TriangleRightIconComponent,
    UploadIconComponent,
    UnlinkIconComponent,
    XIconComponent,

    OpGitlabIssueClosedIconComponent,
    OpGitlabLabelsIconComponent,
    OpGitlabIssueOpenIconComponent,
    OpGitlabMergeRequestClosedIconComponent,
    OpGitlabMergeRequestMergedIconComponent,
    OpGitlabMergeRequestOpenIconComponent,
    OpGitlabMergeRequestReadyIconComponent,
    OpGitlabPipelineStatusCanceledIconComponent,
    OpGitlabPipelineStatusCreatedIconComponent,
    OpGitlabPipelineStatusFailedIconComponent,
    OpGitlabPipelineStatusManualIconComponent,
    OpGitlabPipelineStatusPendingIconComponent,
    OpGitlabPipelineStatusPreparingIconComponent,
    OpGitlabPipelineStatusRunningIconComponent,
    OpGitlabPipelineStatusScheduledIconComponent,
    OpGitlabPipelineStatusSkippedIconComponent,
    OpGitlabPipelineStatusSuccessIconComponent,
    OpGitlabPipelineStatusWaitingIconComponent,

    XCircleIconComponent,

    KebabHorizontalIconComponent,
    ReadIconComponent,
    EyeIconComponent,
    EyeClosedIconComponent,
    ArrowLeftIconComponent,
    GrabberIconComponent,
    PlusIconComponent,
    ReplyIconComponent,
    TriangleDownIconComponent,
    VersionsIconComponent,
    BriefcaseIconComponent,
    CircleSlashIconComponent,
  ],
  declarations: [
    OpIconComponent,
  ],
  providers: [],
  exports: [
    OpIconComponent,

    AlertIconComponent,
    AlertFillIconComponent,
    BugIconComponent,
    ChevronDownIconComponent,
    ChevronLeftIconComponent,
    ChevronRightIconComponent,
    ClockIconComponent,
    CloudIconComponent,
    CopyIconComponent,
    DownloadIconComponent,
    FileDirectoryFillIconComponent,
    FileDirectoryOpenFillIconComponent,
    FileIconComponent,
    FileMediaIconComponent,
    HomeIconComponent,
    InfoIconComponent,
    LinkIconComponent,
    LinkExternalIconComponent,
    ListUnorderedIconComponent,
    OpAddAttachmentIconComponent,
    OpAlarmIconComponent,
    OpAlarmSetIconComponent,
    OpArrowInIconComponent,
    OpBaselineIconComponent,
    OpCursorRectangleSelectIconComponent,
    OpCursorSelectIconComponent,
    OpEnterpriseAddonsIconComponent,
    OpEraseIconComponent,
    OpFileCsvIconComponent,
    OpFileDocIconComponent,
    OpFilePresentationIconComponent,
    OpFileSheetIconComponent,
    OpFileTextIconComponent,
    OpFirstPersonViewIconComponent,
    OpGridMenuIconComponent,
    OpGroupIconComponent,
    OpHierarchyIconComponent,
    OpNoHierarchyIconComponent,
    OpMarkNextcloudIconComponent,
    OpOrthographicPerspectiveIconComponent,
    OpPdfIconComponent,
    OpResizerVerticalLinesIconComponent,
    OpScissorsIconComponent,
    OpStopwatchStartIconComponent,
    OpStopwatchStopIconComponent,
    OpThreedReturnDefaultIconComponent,
    OpTriangleDeltaIconComponent,
    OpViewFitToIconComponent,
    OpViewModalIconComponent,
    OpViewThreedIconComponent,
    PackageIconComponent,
    PaperclipIconComponent,
    PersonIconComponent,
    QuestionIconComponent,
    ScreenFullIconComponent,
    SearchIconComponent,
    ServerIconComponent,
    ShareAndroidIconComponent,
    StarFillIconComponent,
    StarIconComponent,
    TasklistIconComponent,
    TrashIconComponent,
    TriangleRightIconComponent,
    UploadIconComponent,
    UnlinkIconComponent,
    XIconComponent,

    OpGitlabIssueOpenIconComponent,
    OpGitlabIssueClosedIconComponent,
    OpGitlabLabelsIconComponent,
    OpGitlabMergeRequestClosedIconComponent,
    OpGitlabMergeRequestMergedIconComponent,
    OpGitlabMergeRequestOpenIconComponent,
    OpGitlabMergeRequestReadyIconComponent,
    OpGitlabPipelineStatusCanceledIconComponent,
    OpGitlabPipelineStatusCreatedIconComponent,
    OpGitlabPipelineStatusFailedIconComponent,
    OpGitlabPipelineStatusManualIconComponent,
    OpGitlabPipelineStatusPendingIconComponent,
    OpGitlabPipelineStatusPreparingIconComponent,
    OpGitlabPipelineStatusRunningIconComponent,
    OpGitlabPipelineStatusScheduledIconComponent,
    OpGitlabPipelineStatusSkippedIconComponent,
    OpGitlabPipelineStatusSuccessIconComponent,
    OpGitlabPipelineStatusWaitingIconComponent,
    XCircleIconComponent,

    KebabHorizontalIconComponent,
    ReadIconComponent,
    EyeIconComponent,
    EyeClosedIconComponent,
    ArrowLeftIconComponent,
    GrabberIconComponent,
    PlusIconComponent,
    ReplyIconComponent,
    TriangleDownIconComponent,
    VersionsIconComponent,
    BriefcaseIconComponent,
    CircleSlashIconComponent,
  ],
})

export class IconModule {}
