module API
  module V3
    module WorkPackages
      module EagerLoading
        class Base
          def initialize: (untyped work_packages, **untyped options) -> void

          def apply: (untyped _work_package) -> untyped

          def self.module: () -> untyped

          attr_accessor work_packages: untyped
        end

        module NoOp
        end
      end
    end
  end
end
