module API
  module V3
    module WorkPackages
      module EagerLoading
        class Hierarchy < Base
          def apply: (untyped work_package) -> untyped

          private

          def children: (untyped id) -> untyped
        end
      end
    end
  end
end
