module API
  module V3
    module WorkPackages
      module EagerLoading
        class Project < Base
          def apply: (untyped work_package) -> untyped

          private

          def project_for: (untyped project_id) -> untyped

          def projects_by_id: () -> untyped

          def project_ids: () -> untyped
        end
      end
    end
  end
end
