#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# See COPYRIGHT and LICENSE files for more details.
#++

services:
  gitlab:
    volumes:
      # Mount SSL certificates from the host system if you created your own ones
      # Linux
      # - /etc/ssl/certs:/etc/ssl/certs:ro
      # - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
      # In case of MacOS, you need to mount the certs from the host machine
      # having them previously bundled via `sudo update-ca-certificates`
      #
      # - ~/.step/certs:/etc/ssl/certs
      # - ~/.step/certs:/usr/local/share/ca-certificates
    extra_hosts:
      # In case OpenProject is not running via docker compose, forward its traffic to the host gateway
      # - "openproject.${OPENPROJECT_DOCKER_DEV_TLD:-local}:host-gateway"
