module CustomActions::Actions::Strategies::AssociatedCustomField
  include CustomActions::Actions::Strategies::Associated

  include CustomActions::Actions::Strategies::CustomField

  def associated: () -> untyped
end
