class CustomValue::BoolStrategy < CustomValue::FormatStrategy
  def value_present?: () -> untyped

  def typed_value: () -> (nil | untyped)

  def formatted_value: () -> untyped

  def checked?: () -> untyped

  def parse_value: (untyped val) -> untyped

  def validate_type_of_value: () -> nil

  private

  def present?: (untyped val) -> untyped
end
