module OpenProject::TextFormatting::Matchers
  module LinkHandlers
    class WorkPackages < Base
      #
      # Match work package links.
      # Condition: Separator is #|##|###
      # Condition: Prefix is nil
      def applicable?: () -> untyped

      #
      # Examples:
      #
      # #1234, ##1234, ###1234
      def call: () -> (nil | untyped)

      private

      def render_work_package_macro: (untyped wp_id, ?detailed: bool) -> untyped

      def render_work_package_link: (untyped wp_id) -> untyped
    end
  end
end
