module ActiveStorage
  # Abstract base class for the concrete ActiveStorage::Attached::One and ActiveStorage::Attached::Many
  # classes that both provide proxy access to the blob association for a record.
  class Attached
    attr_reader name: String

    attr_reader record: untyped # Model

    def initialize: (String name, untyped record) -> void
  end
end
