#
# Acts as a filter for actions that require password confirmation to have
# passed before it may be accessed.
module PasswordConfirmation
  def check_password_confirmation: () -> (true | false)

  #
  # Returns whether password confirmation has been enabled globally
  # AND the current user is internally authenticated.
  def password_confirmation_required?: () -> untyped
end
