class SCM::StorageUpdaterJob < ApplicationJob
  def perform: (untyped repository) -> (nil | untyped)

  #
  # We don't want to repeat failing jobs here,
  # as they might have failed due to I/O problems and thus,
  # we rather keep the old outdated value until an event
  # triggers the update again.
  def max_attempts: () -> 1
end
