module API
  module V3
    module Memberships
      class FormRepresenter < ::API::Decorators::SimpleForm
        include ::API::Decorators::MetaForm

        def model: () -> untyped

        private

        def payload_representer_class: () -> untyped

        def schema_representer_class: () -> untyped
      end
    end
  end
end
