module Admin::Settings
  class AggregationSettingsController < ::Admin::SettingsController
    def show: () -> untyped

    def default_breadcrumb: () -> untyped

    def show_local_breadcrumb: () -> true
  end
end
