module API
  module V3
    module Capabilities
      module Contexts
        class GlobalRepresenter < ::API::Decorators::Single
          def _type: () -> "CapabilityContext"

          def model_required?: () -> false
        end
      end
    end
  end
end
