class ApplicationRecord < ActiveRecord::Base
end
module Doorkeeper
end
class Doorkeeper::AccessGrant::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Doorkeeper::AccessToken::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Doorkeeper::Application::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module PaperTrail
end
module Migrations::Attachments
end
class Migrations::Attachments::CurrentWikiContent < ActiveRecord::Base
end
module Delayed::Backend::ActiveRecord
end
module ActiveRecord::SessionStore
end
module OpenIDConnect
end
class Attachment::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Journal::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class MaterialBudgetItem::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class CostEntry::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class CostRate::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module TwoFactorAuthentication
end
module Webhooks
end
class Webhooks::Event::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Webhooks::Project::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Project::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Webhooks::Log::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class GithubPullRequest::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module LdapGroups
end
class LdapGroups::SynchronizedGroup::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class LdapGroups::Membership::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module Recaptcha
end
module JobStatus
end
module Storages
end
module Bim::IfcModels
end
module Token
end
module Sessions
end
class WorkPackage::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class LaborBudgetItem::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class TimeEntry::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class MeetingContent::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class MeetingParticipant::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Watcher::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class User::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class WikiPage::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class MenuItems::WikiMenuItem::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class WikiRedirect::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class MenuItem::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class CustomValue::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class CustomOption::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Changeset::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Change::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Message::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module Bim::Bcf
end
class Bim::Bcf::Comment::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Bim::Bcf::Viewpoint::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Comment::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Storages::FileLink::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Storages::ProjectStorage::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class GithubCheckRun::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Storages::LastProjectFolder::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module Grids
end
class Grids::Widget::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Enumeration::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class VersionSetting::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class OrderedWorkPackage::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class View::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ICalTokenQueryAssignment::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Token::ICal::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Workflow::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class MemberRole::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Role::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Type::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Member::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class RolePermission::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Category::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class PaperTrailAudit::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Relation::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Storages::Storage::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class WorkPackageHierarchy::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Journal::AttachableJournal::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Journal::CustomizableJournal::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Notification::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Principal::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class EnabledModule::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Version::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class TimeEntryActivitiesProject::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Query::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class News::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Forum::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Budget::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class NotificationSetting::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Document::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class HourlyRate::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Meeting::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Bim::IfcModels::IfcModel::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Journal::AssociatedJournal < ApplicationRecord
end
module MenuItems
end
module WorkPackages
end
module Projects
end
module Boards
end
module Priority
end
class GroupUser::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class UserPassword::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class DefaultHourlyRate::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class TwoFactorAuthentication::LoginToken::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class TwoFactorAuthentication::Device::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class TwoFactorAuthentication::BackupCode::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module Users
end
module API::Utilities
end
class ApplicationVersion < ApplicationRecord
end
class Journal::BaseJournal < ApplicationRecord
end
class ActiveRecord::Associations::CollectionProxy < ActiveRecord::Relation
end
module Migrations
end
module Delayed
end
module Delayed::Backend
end
module Bim
end
module API
end
class ActiveRecord::Relation < Object
end
module ActiveRecord::Associations
end
