module API
  module V3
    module Projects
      class ProjectCollectionRepresenter < ::API::Decorators::OffsetPaginatedCollection
        def representation_format: (untyped format, mime_type: untyped) -> { href: untyped, identifier: untyped, type: untyped, title: untyped }

        def representation_format_xls: () -> untyped

        def representation_format_csv: () -> untyped

        def paged_models: (untyped models) -> untyped
      end
    end
  end
end
