module AngularHelper
  #
  # Create a component element tag with the given attributes
  #
  # Allow setting dynamic inputs for components with the populateInputsFromDataset functionality
  # by using inputs: { inputName: value }
  def angular_component_tag: (untyped component, ?::Hash[untyped, untyped] options) -> untyped
end
