# Helper module included in ApplicationHelper and ActionController so that
# hooks can be called in views like this:
#
#   <%= call_hook(:some_hook) %>
#   <%= call_hook(:another_hook, foo: 'bar') %>
#
# Or in controllers like:
#   call_hook(:some_hook)
#   call_hook(:another_hook, foo: 'bar')
#
# Hooks added to views will be concatenated into a string. Hooks added to
# controllers will return an array of results.
#
# Several objects are automatically added to the call context:
#
# * project => current project
# * request => Request instance
# * controller => current Controller instance
# * hook_caller => object that called the hook
#
module HookHelper
  def call_hook: (untyped hook, ?::Hash[untyped, untyped] context) -> untyped
end
