module PasswordHelper
  include PasswordConfirmation

  #
  # Decorate the form_for helper with the request-for-confirmation directive
  # when the user is internally authenticated.
  def password_confirmation_form_for: (untyped record, ?::Hash[untyped, untyped] options) { () -> untyped } -> untyped

  #
  # Decorate the form_tag helper with the request-for-confirmation directive
  # when the user is internally authenticated.
  def password_confirmation_form_tag: (?::Hash[untyped, untyped] url_for_options, ?::Hash[untyped, untyped] options) { () -> untyped } -> untyped

  def password_confirmation_data_attribute: (?::Hash[untyped, untyped] with_data) -> untyped

  def render_password_complexity_hint: () -> untyped

  private

  # Return a HTML list with active password complexity rules
  def password_active_rules: () -> untyped

  # Returns a text describing the active password complexity rules,
  # the minimum number of rules to adhere to and the total number of rules.
  def password_rules_description: () -> ("" | untyped)
end
