module ProjectStatusHelper
  def project_status_css_class: (untyped status_code) -> untyped

  def project_status_name: (untyped status_code) -> untyped

  def project_status_name_for_code: (untyped code) -> untyped

  def project_status_ensure_default_code: (untyped status_code) -> untyped
end
