# Group Members

Users and groups can become members of a project. Such a membership will also have one or more roles assigned to it. By that, members control the permissions a user has within a project.

## Linked Properties
|  Link               | Description                                                   | Type             | Constraints                                                    | Supported operations |
|:-------------------:|-----------------------------------------                      | -------------    | -------------------------------------------------------------- | -------------------- |
| self                | This member                                                   | Member           | not null                                                       | READ                 |
| project             | The project for which the membership is granted               | Project          | not null                                                       | READ                 |
| roles               | The list of roles the user or group is granted in the project | RoleCollection   | not null                                                       | READ                 |
| principal           | The user or group that was granted membership                 | User or Group    | not null                                                       | READ                 |

## Local Properties
| Property    | Description                                   | Type        | Constraints                                        | Supported operations |
| :---------: | --------------------------------------------- | ----------- | -----------                                        | -------------------- |
| id          | Member id                                     | Integer     | x > 0                                              | READ                 |
| createdAt   | Time of creation                              | DateTime    | not null                                           | READ                 |

## Member [/api/v3/members/{id}]

+ Model
    + Body

            {
                "_links":
                    "self": {
                        "href": "/api/v3/members/11",
                        "title": "Some user"
                    },
                    "project": {
                        "href": "/api/v3/projects/3",
                        "title": "A project"
                    },
                    "principal": {
                        "href": "/api/v3/users/4",
                        "title": "Some user"
                    },
                    "roles": [
                        {
                            "href": "/api/v3/roles/5",
                            "title": "Member"
                        },
                        {
                            "href": "/api/v3/roles/4",
                            "title": "Reader"
                        }
                    ]
                },
                "_type": "Member",
                "id": 11,
                "createdAt": "2015-03-20T12:56:56Z",
                "_embedded": {
                    "project": "<-- omitted for brevity -->",
                    "principal": "<-- omitted for brevity -->",
                    "roles": [
                        "<-- omitted for brevity -->"
                    ]
                }
            }

## View member [GET]

+ Parameters
    + id (required, integer, `1`) ... member id

+ Response 200 (application/hal+json)

    [Member][]

+ Response 404 (application/hal+json)

    Returned if the member does not exist or the client does not have sufficient permissions
    to see it.

    **Required permission:** view members **or** manage members

    *Note: A client without sufficient permissions shall not be able to test for the existence of
    a member. That's why a 404 is returned here, even if a 403 might be more appropriate.*

    + Body

            {
                "_type": "Error",
                "errorIdentifier": "urn:openproject-org:api:v3:errors:NotFound",
                "message": "The requested resource could not be found."
            }

## Members [/api/v3/members{?filters}]

+ Model
    + Body

            {
                "_links": {
                    "self": { "href": "/api/v3/members" }
                },
                "total": 2,
                "count": 2,
                "_type": "Collection",
                "_embedded":
                {
                    "elements": [
                        {
                            "_links": {
                                "self": { "href": "/api/v3/members/11" }
                            },
                            "_type": "Member",
                            "id": 11,
                            "createdAt": "2015-03-20T12:56:56Z"
                        },
                        {
                            "_links": {
                                "self": { "href": "/api/v3/members/41" }
                            },
                            "_type": "Member",
                            "id": 41,
                            "createdAt": "2019-12-22T12:56:06Z"
                        }
                    ]
                }
            }

## List members [GET]

Returns a collection of members. The client can choose to filter the members similar to how work packages are filtered. In addition to the provided filters, the server will reduce the result set to only contain members, for which the requesting client has sufficient permissions (*view_members*, *manage_members*).

+ Parameters
    + filters (optional, string, `[{ "name": { "operator": "=", "values": ["A User"] }" }]`) ... JSON specifying filter conditions.
    Accepts the same format as returned by the [queries](#queries) endpoint.
    Currently supported filters are:
      + any_name_attribute: filters members based on the name of the principal. All possible name variants (and also email and login) are searched.
      + blocked: reduces the result set to all members that are temporarily blocked or that are not blocked temporarily.
      + group: filters members based on the name of a group. The group however is not the principal used for filtering. Rather, the members of the group are used as the filter values.
      + name: filters members based on the name of the principal. Note that only the name is used which depends on a setting in the OpenProject instance.
      + principal: filters members based on the id of the principal.
      + role: filters members based on the id of any role assigned to the member.
      + status: filters members based on the status of the principal.

+ Response 200 (application/hal+json)

    [Members][]

## Member schema [/api/v3/members/schemas]

+ Model
    + Body

            {
            }

## View member schema [GET]

+ Response 200 (application/hal+json)

    [Member schema][]

+ Response 403 (application/hal+json)

    Returned if the client does not have sufficient permissions to see the schema.

    **Required permission:** manage members or view members on any project

    + Body

            {
                "_type": "Error",
                "errorIdentifier": "urn:openproject-org:api:v3:errors:MissingPermission",
                "message": "You are not authorized to access this resource."
            }

## Member create form [/api/v3/members/form]

This endpoint returns a form allowing a guided creation of new members.

For more details and all possible responses see the general specification of [Forms](#forms).

## Member create form [POST]

+ Request Create member form

    + Body

            {
            }

+ Response 200 (application/hal+json)

    + Body

            {
            }

+ Response 400 (application/hal+json)

    Occurs when the client did not send a valid JSON object in the request body.

    + Body

            {
                "_type": "Error",
                 "errorIdentifier": "urn:openproject-org:api:v3:errors:InvalidRequestBody",
                "message": "The request body was not a single JSON object."
            }

+ Response 403 (application/hal+json)

    Returned if the client does not have sufficient permissions.

    **Required permission:** manage members in any project

    + Body

            {
                "_type": "Error",
                "errorIdentifier": "urn:openproject-org:api:v3:errors:MissingPermission",
                "message": "You are not authorized to access this resource."
            }

## Available Projects [/api/v3/members/available_projects]

+ Model
    + Body

            {
              "_links": {
                "self": {
                  "href": "/api/v3/members/available_projects"
                }
              },
              "_type": "Collection",
              "total": 2,
              "count": 2,
              "_embedded": {
                "elements": [
                  {
                    "_type": "Project",
                    "_links": {
                      "self": {
                        "href": "/api/v3/projects/6",
                        "title": "A project"
                      },
                      "editWorkPackage": {
                        "href": "/api/v3//work_packages/{work_package_id}/form",
                        "templated": true,
                        "method": "post"
                      },
                      "createWorkPackage": {
                        "href": "/api/v3/projects/6/work_packages/form",
                        "method": "post"
                      },
                      "createWorkPackageImmediate": {
                        "href": "/api/v3/projects/6/work_packages",
                        "method": "post"
                      },
                      "categories": {
                        "href": "/api/v3/projects/6/categories"
                      },
                      "members": {
                        "href": "/api/v3/projects/6/members"
                      }
                    },
                    "id": 6,
                    "identifier": "a_project",
                    "name": "A project",
                    "description": "Eveniet molestias omnis quis aut qui eum adipisci. Atque aut aut in exercitationem adipisci amet. Nisi asperiores quia ratione veritatis enim exercitationem magnam. Aut fuga architecto adipisci nihil. Et repellat pariatur. Aliquam et sed perferendis nostrum quaerat. Fugit doloremque voluptatem.",
                    "createdAt": "2015-07-06T13:28:14+00:00",
                    "updatedAt": "2015-10-01T09:55:02+00:00",
                    "type": "Customer Project"
                  },
                  {
                    "_type": "Project",
                    "_links": {
                      "self": {
                        "href": "/api/v3/projects/14",
                        "title": "Another project"
                      },
                      "createWorkPackage": {
                        "href": "/api/v3/projects/14/work_packages/form",
                        "method": "post"
                      },
                      "createWorkPackageImmediate": {
                        "href": "/api/v3/projects/14/work_packages",
                        "method": "post"
                      },
                      "categories": {
                        "href": "/api/v3/projects/14/categories"
                      },
                      "members": {
                        "href": "/api/v3/projects/14/members"
                      }
                    },
                    "id": 14,
                    "identifier": "another_project",
                    "name": "Another project",
                    "description": "",
                    "createdAt": "2016-02-29T12:50:20+00:00",
                    "updatedAt": "2016-02-29T12:50:20+00:00",
                    "type": null
                  }]
                }
              }
            }

## Available projects [GET]

Gets a list of projects in which a member can be created in. The list contains all projects in which the user issuing the request has the manage versions permissions.

+ Response 200 (application/hal+json)

    [Available Projects][]

+ Response 403 (application/hal+json)

    Returned if the client does not have sufficient permissions.

    **Required permission:** manage members

    + Body

            {
                "_type": "Error",
                "errorIdentifier": "urn:openproject-org:api:v3:errors:MissingPermission",
                "message": "You are not authorized to access this resource."
            }
