module API
  module V3
    module Queries
      module Schemas
        class AllPrincipalsFilterDependencyRepresenter < PrincipalFilterDependencyRepresenter
          def json_cache_key: () -> untyped

          private

          def filter_query: () -> untyped
        end
      end
    end
  end
end
