module API
  module V3
    module Queries
      module Schemas
        class CategoryFilterDependencyRepresenter < FilterDependencyRepresenter
          def json_cache_key: () -> untyped

          def href_callback: () -> untyped

          def type: () -> "[]Category"
        end
      end
    end
  end
end
