module API
  module V3
    module Queries
      module Schemas
        class ProjectFilterDependencyRepresenter < FilterDependencyRepresenter
          def href_callback: () -> ::String

          def type: () -> "[]Project"
        end
      end
    end
  end
end
