module API
  module V3
    module Queries
      module Schemas
        class TextFilterDependencyRepresenter < FilterDependencyRepresenter
          def href_callback: () -> nil

          private

          def type: () -> "[1]String"
        end
      end
    end
  end
end
