module LdapGroups
  class SynchronizedFilter < ::ApplicationRecord
    extend _ActiveRecord_Relation_ClassMethods[LdapGroups::SynchronizedFilter, ActiveRecord_Relation, Integer]

    module GeneratedAttributeMethods
      def id: () -> Integer

      def id=: (Integer) -> Integer

      def id?: () -> bool

      def id_changed?: () -> bool

      def id_change: () -> [ Integer?, Integer? ]

      def id_will_change!: () -> void

      def id_was: () -> Integer?

      def id_previously_changed?: () -> bool

      def id_previous_change: () -> Array[Integer?]?

      def id_previously_was: () -> Integer?

      def id_before_last_save: () -> Integer?

      def id_change_to_be_saved: () -> Array[Integer?]?

      def id_in_database: () -> Integer?

      def saved_change_to_id: () -> Array[Integer?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def name: () -> String?

      def name=: (String?) -> String?

      def name?: () -> bool

      def name_changed?: () -> bool

      def name_change: () -> [ String?, String? ]

      def name_will_change!: () -> void

      def name_was: () -> String?

      def name_previously_changed?: () -> bool

      def name_previous_change: () -> Array[String?]?

      def name_previously_was: () -> String?

      def name_before_last_save: () -> String?

      def name_change_to_be_saved: () -> Array[String?]?

      def name_in_database: () -> String?

      def saved_change_to_name: () -> Array[String?]?

      def saved_change_to_name?: () -> bool

      def will_save_change_to_name?: () -> bool

      def restore_name!: () -> void

      def clear_name_change: () -> void

      def group_name_attribute: () -> String?

      def group_name_attribute=: (String?) -> String?

      def group_name_attribute?: () -> bool

      def group_name_attribute_changed?: () -> bool

      def group_name_attribute_change: () -> [ String?, String? ]

      def group_name_attribute_will_change!: () -> void

      def group_name_attribute_was: () -> String?

      def group_name_attribute_previously_changed?: () -> bool

      def group_name_attribute_previous_change: () -> Array[String?]?

      def group_name_attribute_previously_was: () -> String?

      def group_name_attribute_before_last_save: () -> String?

      def group_name_attribute_change_to_be_saved: () -> Array[String?]?

      def group_name_attribute_in_database: () -> String?

      def saved_change_to_group_name_attribute: () -> Array[String?]?

      def saved_change_to_group_name_attribute?: () -> bool

      def will_save_change_to_group_name_attribute?: () -> bool

      def restore_group_name_attribute!: () -> void

      def clear_group_name_attribute_change: () -> void

      def filter_string: () -> String?

      def filter_string=: (String?) -> String?

      def filter_string?: () -> bool

      def filter_string_changed?: () -> bool

      def filter_string_change: () -> [ String?, String? ]

      def filter_string_will_change!: () -> void

      def filter_string_was: () -> String?

      def filter_string_previously_changed?: () -> bool

      def filter_string_previous_change: () -> Array[String?]?

      def filter_string_previously_was: () -> String?

      def filter_string_before_last_save: () -> String?

      def filter_string_change_to_be_saved: () -> Array[String?]?

      def filter_string_in_database: () -> String?

      def saved_change_to_filter_string: () -> Array[String?]?

      def saved_change_to_filter_string?: () -> bool

      def will_save_change_to_filter_string?: () -> bool

      def restore_filter_string!: () -> void

      def clear_filter_string_change: () -> void

      def auth_source_id: () -> Integer?

      def auth_source_id=: (Integer?) -> Integer?

      def auth_source_id?: () -> bool

      def auth_source_id_changed?: () -> bool

      def auth_source_id_change: () -> [ Integer?, Integer? ]

      def auth_source_id_will_change!: () -> void

      def auth_source_id_was: () -> Integer?

      def auth_source_id_previously_changed?: () -> bool

      def auth_source_id_previous_change: () -> Array[Integer?]?

      def auth_source_id_previously_was: () -> Integer?

      def auth_source_id_before_last_save: () -> Integer?

      def auth_source_id_change_to_be_saved: () -> Array[Integer?]?

      def auth_source_id_in_database: () -> Integer?

      def saved_change_to_auth_source_id: () -> Array[Integer?]?

      def saved_change_to_auth_source_id?: () -> bool

      def will_save_change_to_auth_source_id?: () -> bool

      def restore_auth_source_id!: () -> void

      def clear_auth_source_id_change: () -> void

      def created_at: () -> ActiveSupport::TimeWithZone

      def created_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: () -> bool

      def created_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: () -> bool

      def created_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> Array[ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: () -> bool

      def will_save_change_to_created_at?: () -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def updated_at: () -> ActiveSupport::TimeWithZone

      def updated_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

      def updated_at?: () -> bool

      def updated_at_changed?: () -> bool

      def updated_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

      def updated_at_will_change!: () -> void

      def updated_at_was: () -> ActiveSupport::TimeWithZone?

      def updated_at_previously_changed?: () -> bool

      def updated_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

      def updated_at_previously_was: () -> ActiveSupport::TimeWithZone?

      def updated_at_before_last_save: () -> ActiveSupport::TimeWithZone?

      def updated_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

      def updated_at_in_database: () -> ActiveSupport::TimeWithZone?

      def saved_change_to_updated_at: () -> Array[ActiveSupport::TimeWithZone?]?

      def saved_change_to_updated_at?: () -> bool

      def will_save_change_to_updated_at?: () -> bool

      def restore_updated_at!: () -> void

      def clear_updated_at_change: () -> void

      def base_dn: () -> String?

      def base_dn=: (String?) -> String?

      def base_dn?: () -> bool

      def base_dn_changed?: () -> bool

      def base_dn_change: () -> [ String?, String? ]

      def base_dn_will_change!: () -> void

      def base_dn_was: () -> String?

      def base_dn_previously_changed?: () -> bool

      def base_dn_previous_change: () -> Array[String?]?

      def base_dn_previously_was: () -> String?

      def base_dn_before_last_save: () -> String?

      def base_dn_change_to_be_saved: () -> Array[String?]?

      def base_dn_in_database: () -> String?

      def saved_change_to_base_dn: () -> Array[String?]?

      def saved_change_to_base_dn?: () -> bool

      def will_save_change_to_base_dn?: () -> bool

      def restore_base_dn!: () -> void

      def clear_base_dn_change: () -> void

      def sync_users: () -> bool

      def sync_users=: (bool) -> bool

      def sync_users?: () -> bool

      def sync_users_changed?: () -> bool

      def sync_users_change: () -> [ bool?, bool? ]

      def sync_users_will_change!: () -> void

      def sync_users_was: () -> bool?

      def sync_users_previously_changed?: () -> bool

      def sync_users_previous_change: () -> Array[bool?]?

      def sync_users_previously_was: () -> bool?

      def sync_users_before_last_save: () -> bool?

      def sync_users_change_to_be_saved: () -> Array[bool?]?

      def sync_users_in_database: () -> bool?

      def saved_change_to_sync_users: () -> Array[bool?]?

      def saved_change_to_sync_users?: () -> bool

      def will_save_change_to_sync_users?: () -> bool

      def restore_sync_users!: () -> void

      def clear_sync_users_change: () -> void
    end
    include GeneratedAttributeMethods
    def groups: () -> LdapGroups::SynchronizedGroup::ActiveRecord_Associations_CollectionProxy
    def groups=: (LdapGroups::SynchronizedGroup::ActiveRecord_Associations_CollectionProxy | Array[LdapGroups::SynchronizedGroup]) -> (LdapGroups::SynchronizedGroup::ActiveRecord_Associations_CollectionProxy | Array[LdapGroups::SynchronizedGroup])
    def group_ids: () -> Array[Integer]
    def group_ids=: (Array[Integer]) -> Array[Integer]

    def auth_source: () -> AuthSource
    def auth_source=: (AuthSource?) -> AuthSource?
    def reload_auth_source: () -> AuthSource?
    def build_auth_source: (untyped) -> AuthSource
    def create_auth_source: (untyped) -> AuthSource
    def create_auth_source!: (untyped) -> AuthSource
    module GeneratedAssociationMethods
    end
    include GeneratedAssociationMethods

    module GeneratedRelationMethods
    end

    class ActiveRecord_Relation < ::ActiveRecord::Relation
      include GeneratedRelationMethods
      include _ActiveRecord_Relation[LdapGroups::SynchronizedFilter, Integer]
      include Enumerable[LdapGroups::SynchronizedFilter]
    end

    class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include GeneratedRelationMethods
      include _ActiveRecord_Relation[LdapGroups::SynchronizedFilter, Integer]
    end
  end
end
