module Users
  class UpdateContract < BaseContract
    private

    #
    # Users can only be updated when
    # - the user is editing herself
    # - the user has the global manage_user CRU permission
    # - the user is an admin
    def user_allowed_to_update: () -> (untyped | nil)
  end
end
