#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# See COPYRIGHT and LICENSE files for more details.
#++

# The following overrides should be copied to the core docker-compose.overrides.yml in the main directory.
# Only use them if you DO NOT use the TLS setup.
# If you use the TLS setup, ignore the following values and instead see
# tls/docker-compose.core-override.example.yml for the minio TLS setup values.

services:
  backend:
    environment:
     OPENPROJECT_ATTACHMENTS__STORAGE: "fog"
     OPENPROJECT_FOG_DIRECTORY: "openproject-uploads"
     OPENPROJECT_FOG_CREDENTIALS_PROVIDER: "AWS" # Minio is S3 compliant, so we can use the AWS provider
     OPENPROJECT_FOG_CREDENTIALS_ENDPOINT: "http://127.0.0.1:9000" # URI for your MinIO instance
     OPENPROJECT_FOG_CREDENTIALS_AWS__ACCESS__KEY__ID: "minioadmin"
     OPENPROJECT_FOG_CREDENTIALS_AWS__SECRET__ACCESS__KEY: "minioadmin"
     OPENPROJECT_FOG_CREDENTIALS_PATH__STYLE: "true"
     OPENPROJECT_FOG_CREDENTIALS_REGION: "us-east-1"
     OPENPROJECT_DEV_EXTRA_HOSTS: "${OPENPROJECT_DEV_HOST},http://127.0.0.1:9000"
