#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# See COPYRIGHT and LICENSE files for more details.
#++

services:
  # local S3 storage for development
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Admin Console (Management UI) port
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    entrypoint: sh
    # minio automatically maps folders to buckets, so we create the bucket here before starting the server
    command: -c 'mkdir -p /data/openproject-uploads && /usr/bin/minio server --console-address ":9001" /data'
    networks:
      - external
    labels:
      - "traefik.enable=true"
      # MinIO API
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.rule=Host(`minio.${OPENPROJECT_DOCKER_DEV_TLD:-local}`)"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.routers.minio.tls.certresolver=step"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      # MinIO Admin Console (Management UI)
      - "traefik.http.routers.minioadmin.entrypoints=websecure"
      - "traefik.http.routers.minioadmin.rule=Host(`minioadmin.${OPENPROJECT_DOCKER_DEV_TLD:-local}`)"
      - "traefik.http.routers.minioadmin.service=minioadmin"
      - "traefik.http.routers.minioadmin.tls.certresolver=step"
      - "traefik.http.services.minioadmin.loadbalancer.server.port=9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:

networks:
  external:
    name: gateway
    external: true
