module OpenProject::TextFormatting::Formats
  module Plain
    class Formatter < OpenProject::TextFormatting::Formats::BaseFormatter
      def to_html: (untyped text) -> untyped

      def to_document: (untyped text) -> untyped

      def filters: () -> ::Array[untyped]

      def self.format: () -> :plain
    end
  end
end
