#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# See COPYRIGHT and LICENSE files for more details.
#++

services:
  nextcloud:
    image: nextcloud:stable
    restart: unless-stopped
    networks:
      - gateway
    volumes:
      - nextcloud:/var/www/html
      #   If you want to use a local version of a plugin, mount a local folder
      #   more detailed instructions available at https://github.com/nextcloud/integration_openproject/blob/master/docs/setup_via_docker.md
      # - ../nextcloud_apps:/var/www/html/custom_apps
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${OPENPROJECT_DOCKER_DEV_TLD:-local}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"

  cron:
    image: nextcloud:stable
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
      #   If you want to use a local version of a plugin, mount a local folder
      #   more detailed instructions available at https://github.com/nextcloud/integration_openproject/blob/master/docs/setup_via_docker.md
      # - ../nextcloud_apps:/var/www/html/custom_apps
    networks:
      - gateway
    entrypoint: /cron.sh

networks:
  gateway:
    external: true
    name: gateway

volumes:
  nextcloud:
