#!/bin/bash

APP_NAME="_APP_NAME_"
CLI="${APP_NAME}"
SVN_REPOSITORIES=$(${CLI} config:get SVN_REPOSITORIES)
PORT=$(${CLI} config:get PORT)
SYS_API_KEY=$(${CLI} config:get SYS_API_KEY)
APP_GROUP=$(${CLI} config:get APP_GROUP)

/opt/${APP_NAME}/bin/ruby /opt/${APP_NAME}/extra/svn/reposman.rb \
  --openproject-host "http://127.0.0.1:${PORT}" \
  --owner "www-data" \
  --group "${APP_GROUP}" \
  --public-mode '2750' \
  --private-mode '2750' \
  --svn-dir "${SVN_REPOSITORIES}" \
  --url "file://${SVN_REPOSITORIES}" \
  --key "${SYS_API_KEY}" \
  --scm Subversion \
  --verbose

