#!/bin/bash -e

HOST="${HOST:=127.0.0.1}"
PORT="${PORT:=8080}"
RAILS_ENV="${RAILS_ENV:="development"}"

USE_PUMA="${USE_PUMA:="false"}"

if [ "$USE_PUMA" = "true" ]; then
  bundle exec rails server -u puma -b $HOST -p $PORT
else
  bundle exec unicorn --config-file config/unicorn.rb --host $HOST --port $PORT --env $RAILS_ENV
fi
