module Groups
  class CleanupInheritedRolesService < ::BaseServices::BaseContracted
    include Groups::Concerns::MembershipManipulation

    def initialize: (untyped group, current_user: untyped, ?contract_class: untyped) -> void

    private

    def modify_members_and_roles: (untyped params) -> untyped

    def remove_member_roles_sql: (untyped member_role_ids) -> (untyped | ::String)

    def members_to_remove: (untyped member_ids) -> untyped

    def remove_members: (untyped members) -> untyped
  end
end
