class Reports::SubprojectReport < Reports::Report
  def self.report_type: () -> "subproject"

  def field: () -> "project_id"

  def rows: () -> untyped

  def data: () -> untyped

  def title: () -> untyped
end
