# - copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2023 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
# +
module Bim
  module DemoData
    class IfcModelSeeder < ::Seeder
      attr_reader project: untyped

      attr_reader project_data: untyped

      def initialize: (untyped project, untyped project_data) -> void

      def seed_data!: () -> (nil | untyped)

      private

      def seed_model: (untyped model) -> untyped

      def create_model: (untyped model, untyped user, untyped xkt_data) -> untyped

      def create_model_container: (untyped project, untyped user, untyped title, untyped default) -> untyped

      def add_ifc_model_attachment: (untyped model_container, untyped user, untyped file, untyped description) -> untyped

      def get_xkt_file: (untyped name) -> (nil | untyped)
    end
  end
end
