module API
  module Decorators
    module CreateForm
      def form_url: () -> untyped

      def resource_url: () -> untyped

      def commit_method: () -> :post

      def contract_class: () -> untyped

      private

      def downcase_model_name: () -> untyped
    end
  end
end
