module Webhooks
  class Project < ::ApplicationRecord
    extend _ActiveRecord_Relation_ClassMethods[Webhooks::Project, ActiveRecord_Relation, Integer]

    module GeneratedAttributeMethods
      def id: () -> Integer

      def id=: (Integer) -> Integer

      def id?: () -> bool

      def id_changed?: () -> bool

      def id_change: () -> [ Integer?, Integer? ]

      def id_will_change!: () -> void

      def id_was: () -> Integer?

      def id_previously_changed?: () -> bool

      def id_previous_change: () -> Array[Integer?]?

      def id_previously_was: () -> Integer?

      def id_before_last_save: () -> Integer?

      def id_change_to_be_saved: () -> Array[Integer?]?

      def id_in_database: () -> Integer?

      def saved_change_to_id: () -> Array[Integer?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def project_id: () -> Integer?

      def project_id=: (Integer?) -> Integer?

      def project_id?: () -> bool

      def project_id_changed?: () -> bool

      def project_id_change: () -> [ Integer?, Integer? ]

      def project_id_will_change!: () -> void

      def project_id_was: () -> Integer?

      def project_id_previously_changed?: () -> bool

      def project_id_previous_change: () -> Array[Integer?]?

      def project_id_previously_was: () -> Integer?

      def project_id_before_last_save: () -> Integer?

      def project_id_change_to_be_saved: () -> Array[Integer?]?

      def project_id_in_database: () -> Integer?

      def saved_change_to_project_id: () -> Array[Integer?]?

      def saved_change_to_project_id?: () -> bool

      def will_save_change_to_project_id?: () -> bool

      def restore_project_id!: () -> void

      def clear_project_id_change: () -> void

      def webhooks_webhook_id: () -> Integer?

      def webhooks_webhook_id=: (Integer?) -> Integer?

      def webhooks_webhook_id?: () -> bool

      def webhooks_webhook_id_changed?: () -> bool

      def webhooks_webhook_id_change: () -> [ Integer?, Integer? ]

      def webhooks_webhook_id_will_change!: () -> void

      def webhooks_webhook_id_was: () -> Integer?

      def webhooks_webhook_id_previously_changed?: () -> bool

      def webhooks_webhook_id_previous_change: () -> Array[Integer?]?

      def webhooks_webhook_id_previously_was: () -> Integer?

      def webhooks_webhook_id_before_last_save: () -> Integer?

      def webhooks_webhook_id_change_to_be_saved: () -> Array[Integer?]?

      def webhooks_webhook_id_in_database: () -> Integer?

      def saved_change_to_webhooks_webhook_id: () -> Array[Integer?]?

      def saved_change_to_webhooks_webhook_id?: () -> bool

      def will_save_change_to_webhooks_webhook_id?: () -> bool

      def restore_webhooks_webhook_id!: () -> void

      def clear_webhooks_webhook_id_change: () -> void
    end
    include GeneratedAttributeMethods

    def webhook: () -> Webhooks::Webhook
    def webhook=: (Webhooks::Webhook?) -> Webhooks::Webhook?
    def reload_webhook: () -> Webhooks::Webhook?
    def build_webhook: (untyped) -> Webhooks::Webhook
    def create_webhook: (untyped) -> Webhooks::Webhook
    def create_webhook!: (untyped) -> Webhooks::Webhook
    def project: () -> Project
    def project=: (Project?) -> Project?
    def reload_project: () -> Project?
    def build_project: (untyped) -> Project
    def create_project: (untyped) -> Project
    def create_project!: (untyped) -> Project
    module GeneratedAssociationMethods
    end
    include GeneratedAssociationMethods

    module GeneratedRelationMethods
    end

    class ActiveRecord_Relation < ::ActiveRecord::Relation
      include GeneratedRelationMethods
      include _ActiveRecord_Relation[Webhooks::Project, Integer]
      include Enumerable[Webhooks::Project]
    end

    class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include GeneratedRelationMethods
      include _ActiveRecord_Relation[Webhooks::Project, Integer]
    end
  end
end
