<!-- include(introduction.apib) -->
<!-- include(basic-objects.apib) -->
<!-- include(filters.apib) -->
<!-- include(group-objects.apib) -->

<!-- include(endpoints/activities.apib) -->
<!-- include(endpoints/attachments.apib) -->
<!-- include(endpoints/categories.apib) -->
<!-- include(endpoints/configuration.apib) -->
<!-- include(endpoints/custom-actions.apib) -->
<!-- include(endpoints/custom-options.apib) -->
<!-- include(endpoints/documents.apib) -->
<!-- include(endpoints/forms.apib) -->
<!-- include(endpoints/grids.apib) -->
<!-- include(endpoints/groups.apib) -->
<!-- include(endpoints/help_texts.apib) -->
<!-- include(endpoints/members.apib) -->
<!-- include(endpoints/news.apib) -->
<!-- include(endpoints/posts.apib) -->
<!-- include(endpoints/principals.apib) -->
<!-- include(endpoints/priorities.apib) -->
<!-- include(endpoints/projects.apib) -->
<!-- include(endpoints/queries.apib) -->
<!-- include(endpoints/relations.apib) -->
<!-- include(endpoints/render.apib) -->
<!-- include(endpoints/revisions.apib) -->
<!-- include(endpoints/roles.apib) -->
<!-- include(endpoints/root.apib) -->
<!-- include(endpoints/schemas.apib) -->
<!-- include(endpoints/statuses.apib) -->
<!-- include(endpoints/string-objects.apib) -->
<!-- include(endpoints/time_entries.apib) -->
<!-- include(endpoints/types.apib) -->
<!-- include(endpoints/user-preferences.apib) -->
<!-- include(endpoints/users.apib) -->
<!-- include(endpoints/versions.apib) -->
<!-- include(endpoints/wiki_pages.apib) -->
<!-- include(endpoints/work-packages.apib) -->
