#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# See COPYRIGHT and LICENSE files for more details.
#++

services:
  web:
    image: xwiki:stable-postgres-tomcat
    depends_on:
      - db
    environment:
      - DB_USER=${XWIKI_DB_USER:-xwiki}
      - DB_PASSWORD=${XWIKI_DB_PASSWORD:-xwiki}
      - DB_HOST=db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xwiki.rule=Host(`xwiki.${OPENPROJECT_DOCKER_DEV_TLD:-local}`)"
      - "traefik.http.routers.xwiki.entrypoints=websecure"
    volumes:
      - xwiki-data:/usr/local/xwiki
    networks:
      - bridge
      - gateway
  db:
    image: postgres:17
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_ROOT_PASSWORD=${XWIKI_DB_ROOT_PASSWORD:-xwiki}
      - POSTGRES_PASSWORD=${XWIKI_DB_PASSWORD:-xwiki}
      - POSTGRES_USER=${XWIKI_DB_USER:-xwiki}
      - POSTGRES_DB=${XWIKI_DB_NAME:-xwiki}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale-provider=builtin --locale=C.UTF-8
    networks:
      - bridge

volumes:
  postgres-data:
  xwiki-data:

networks:
  bridge:
    driver: bridge
  gateway:
    external: true
    name: gateway
