class RbStoriesController < RbApplicationController
  include OpenProject::PDFExport::ExportCard

  # This is a constant here because we will recruit it elsewhere to whitelist
  # attributes. This is necessary for now as we still directly use `attributes=`
  # in non-controller code.
  PERMITTED_PARAMS: ::Array[:id | :status_id | :version_id | :story_points | :type_id | :subject | :author_id | :sprint_id]

  def create: () -> untyped

  def update: () -> untyped

  private

  def respond_with_story: (untyped call) -> untyped

  def story_params: () -> untyped
end
