module API
  module V3
    module Principals
      module PrincipalType
        #
        # Return the appropriate API level type
        # that depend on the AR type of the principal passed in.
        def self?.for: (untyped principal) -> untyped
      end
    end
  end
end
