module Bim::Bcf::API::V2_1::Endpoints
  class Show < API::Utilities::Endpoints::Show
    def render: (untyped request) -> untyped

    private

    def deduce_render_representer: () -> untyped
  end
end
