module Bim::Bcf::API::V2_1::Endpoints
  class Update < API::Utilities::Endpoints::Update
    include ModifyMixin

    def present_success: (untyped _request, untyped call) -> untyped

    def postprocess_errors: (untyped call) -> untyped
  end
end
