module TwoFactorAuthentication
  class RememberedAuthToken < ::Token::HashedToken
    extend _ActiveRecord_Relation_ClassMethods[TwoFactorAuthentication::RememberedAuthToken, ActiveRecord_Relation, Integer]

    module GeneratedAttributeMethods
      def id: () -> Integer

      def id=: (Integer) -> Integer

      def id?: () -> bool

      def id_changed?: () -> bool

      def id_change: () -> [ Integer?, Integer? ]

      def id_will_change!: () -> void

      def id_was: () -> Integer?

      def id_previously_changed?: () -> bool

      def id_previous_change: () -> Array[Integer?]?

      def id_previously_was: () -> Integer?

      def id_before_last_save: () -> Integer?

      def id_change_to_be_saved: () -> Array[Integer?]?

      def id_in_database: () -> Integer?

      def saved_change_to_id: () -> Array[Integer?]?

      def saved_change_to_id?: () -> bool

      def will_save_change_to_id?: () -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def user_id: () -> Integer?

      def user_id=: (Integer?) -> Integer?

      def user_id?: () -> bool

      def user_id_changed?: () -> bool

      def user_id_change: () -> [ Integer?, Integer? ]

      def user_id_will_change!: () -> void

      def user_id_was: () -> Integer?

      def user_id_previously_changed?: () -> bool

      def user_id_previous_change: () -> Array[Integer?]?

      def user_id_previously_was: () -> Integer?

      def user_id_before_last_save: () -> Integer?

      def user_id_change_to_be_saved: () -> Array[Integer?]?

      def user_id_in_database: () -> Integer?

      def saved_change_to_user_id: () -> Array[Integer?]?

      def saved_change_to_user_id?: () -> bool

      def will_save_change_to_user_id?: () -> bool

      def restore_user_id!: () -> void

      def clear_user_id_change: () -> void

      def type: () -> String?

      def type=: (String?) -> String?

      def type?: () -> bool

      def type_changed?: () -> bool

      def type_change: () -> [ String?, String? ]

      def type_will_change!: () -> void

      def type_was: () -> String?

      def type_previously_changed?: () -> bool

      def type_previous_change: () -> Array[String?]?

      def type_previously_was: () -> String?

      def type_before_last_save: () -> String?

      def type_change_to_be_saved: () -> Array[String?]?

      def type_in_database: () -> String?

      def saved_change_to_type: () -> Array[String?]?

      def saved_change_to_type?: () -> bool

      def will_save_change_to_type?: () -> bool

      def restore_type!: () -> void

      def clear_type_change: () -> void

      def value: () -> String

      def value=: (String) -> String

      def value?: () -> bool

      def value_changed?: () -> bool

      def value_change: () -> [ String?, String? ]

      def value_will_change!: () -> void

      def value_was: () -> String?

      def value_previously_changed?: () -> bool

      def value_previous_change: () -> Array[String?]?

      def value_previously_was: () -> String?

      def value_before_last_save: () -> String?

      def value_change_to_be_saved: () -> Array[String?]?

      def value_in_database: () -> String?

      def saved_change_to_value: () -> Array[String?]?

      def saved_change_to_value?: () -> bool

      def will_save_change_to_value?: () -> bool

      def restore_value!: () -> void

      def clear_value_change: () -> void

      def created_at: () -> ActiveSupport::TimeWithZone

      def created_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: () -> bool

      def created_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: () -> bool

      def created_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> Array[ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: () -> bool

      def will_save_change_to_created_at?: () -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def expires_on: () -> ActiveSupport::TimeWithZone?

      def expires_on=: (ActiveSupport::TimeWithZone?) -> ActiveSupport::TimeWithZone?

      def expires_on?: () -> bool

      def expires_on_changed?: () -> bool

      def expires_on_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

      def expires_on_will_change!: () -> void

      def expires_on_was: () -> ActiveSupport::TimeWithZone?

      def expires_on_previously_changed?: () -> bool

      def expires_on_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

      def expires_on_previously_was: () -> ActiveSupport::TimeWithZone?

      def expires_on_before_last_save: () -> ActiveSupport::TimeWithZone?

      def expires_on_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

      def expires_on_in_database: () -> ActiveSupport::TimeWithZone?

      def saved_change_to_expires_on: () -> Array[ActiveSupport::TimeWithZone?]?

      def saved_change_to_expires_on?: () -> bool

      def will_save_change_to_expires_on?: () -> bool

      def restore_expires_on!: () -> void

      def clear_expires_on_change: () -> void
    end
    include GeneratedAttributeMethods

    def user: () -> User
    def user=: (User?) -> User?
    def reload_user: () -> User?
    def build_user: (untyped) -> User
    def create_user: (untyped) -> User
    def create_user!: (untyped) -> User
    module GeneratedAssociationMethods
    end
    include GeneratedAssociationMethods

    module GeneratedRelationMethods
    end

    class ActiveRecord_Relation < ::ActiveRecord::Relation
      include GeneratedRelationMethods
      include _ActiveRecord_Relation[TwoFactorAuthentication::RememberedAuthToken, Integer]
      include Enumerable[TwoFactorAuthentication::RememberedAuthToken]
    end

    class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include GeneratedRelationMethods
      include _ActiveRecord_Relation[TwoFactorAuthentication::RememberedAuthToken, Integer]
    end
  end
end
