#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# See COPYRIGHT and LICENSE files for more details.
#++

# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks
#
# This configuration file is only used to check interpolations consistency with command
# `i18n-tasks check-consistent-interpolations --config config/i18n-tasks-all-files.yml`

data:
  # Locale files patterns where translations are read from:
  read:
    - config/locales/en.seeders.yml
    - config/locales/en.yml
    - config/locales/js-en.yml
    - config/locales/crowdin/%{locale}.seeders.yml
    - config/locales/crowdin/%{locale}.yml
    - config/locales/crowdin/js-%{locale}.yml
    - config/locales/generated/%{locale}.yml
    - modules/*/config/locales/en.seeders.yml
    - modules/*/config/locales/en.yml
    - modules/*/config/locales/js-en.yml
    - modules/*/config/locales/crowdin/%{locale}.seeders.yml
    - modules/*/config/locales/crowdin/%{locale}.yml
    - modules/*/config/locales/crowdin/js-%{locale}.yml

ignore_inconsistent_interpolations:
  # Ignore interpolations checks in the singular form.
  # Some languages have simple pluralization form where 'one' is only used for exactly 1 item.
  # Other languages such as Ukrainian and Serbian use 'one' also for 21, 31, 101, etc.
  # Those will use the %{count} interpolation while the english source language will not have it.
  - '*.one'
