module API
  module V3
    module Budgets
      class BudgetRepresenter < ::API::Decorators::Single
        include API::Caching::CachedRepresenter

        include ::API::V3::Attachments::AttachableRepresenterMixin

        def _type: () -> "Budget"
      end
    end
  end
end
