#!/bin/sh

set -e
set -u

cmd="$@"

while ! curl -sSL "${SELENIUM_GRID_URL}/status" 2>&1 \
        | jq -r '.value.ready' 2>&1 | grep "true" >/dev/null; do
    echo 'Waiting for the Grid'
    sleep 1
done

>&2 echo "Selenium Grid is up - executing $cmd"
exec $cmd
