// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/99c4fb76b5d941939ba53e61d0daee4bd74f150f/rx/rx.binding.d.ts
declare module "rx.binding" {
	export = Rx;
}