listen_addresses = '*'
shared_buffers = 4GB
work_mem = 32MB
maintenance_work_mem = 512MB
effective_cache_size = 16GB
wal_buffers = 64MB
effective_io_concurrency = 200
random_page_cost = 1.1
checkpoint_completion_target = 0.9
default_statistics_target = 200
max_connections = 100
log_min_duration_statement = 500
