module API
  module V3
    module FileLinks
      # PayloadRepresenter mixin will filter out read-only attributes from user
      # params input.
      #
      # Used by: ParseCreateParamsService, in parent class.
      class FileLinkPayloadRepresenter < FileLinkRepresenter
        include ::API::Utilities::PayloadRepresenter
      end
    end
  end
end
