module Queries::WorkPackages
  module Common
    module ManualSorting
      #
      # We depend on ordered_work_packages association
      # for determining sort and filter for manual sorting.
      #
      # We could restrict the join result with where(query_id: context.id) later
      # but that prevents the execution planner from optimizing on the explicit join clause.
      def ordered_work_packages_join: (untyped query) -> untyped
    end
  end
end
