#!/usr/bin/env ruby

require "pathname"
require "tempfile"

openapi_yaml_spec_path = Pathname(__dir__).join("../../tmp/oas-generated.yml")
full_spec = `#{Pathname(__dir__).join("spec")} --format yaml`
status = $?.exitstatus
if status != 0
  warn "failed to bundle the openapi spec yaml file"
  exit status
end

status = 1

begin
  File.open(openapi_yaml_spec_path, "w+") do |file|
    file.puts full_spec
  end

  lint_args = []
  limit_arg = ARGV.find { |arg| arg.start_with?("--limit=") }
  lint_args << "--max-problems=#{limit_arg.delete_prefix('--limit=')}" unless limit_arg.nil?

  system("npx @redocly/cli lint --config=.redocly.yaml #{openapi_yaml_spec_path} #{lint_args.join(' ')}")

  status = $?.exitstatus
ensure
  FileUtils.rm_f openapi_yaml_spec_path
end

exit status
