module Users
  class ChangePasswordService
    attr_accessor current_user: untyped

    attr_accessor session: untyped

    def initialize: (current_user: untyped, session: untyped) -> void

    def call: (untyped params) -> untyped

    private

    def invalidate_recovery_tokens: () -> untyped

    def invalidate_session_result: () -> untyped

    def log_success: () -> untyped

    def log_failure: () -> untyped
  end
end
