// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/bcd5761826eb567876c197ccc6a87c4d05731054/moment/moment.d.ts
declare var moment: moment.MomentStatic;