module Projects::Copy
  class VersionsDependentService < Dependency
    def self.human_name: () -> untyped

    def source_count: () -> untyped

    def copy_dependency: (params: untyped) -> untyped
  end
end
