module ActiveRecord
  module Inheritance
    module ClassMethods
      def primary_abstract_class: () -> void
    end
  end

  module Enum
    def enum: (**untyped options) -> void
            | ((String | Symbol) name, **untyped options) -> void
            | ((String | Symbol) name, (Hash[(Symbol | String), untyped] | Array[Symbol | String]) values, **untyped options) -> void
  end
end
