module Users::Scopes
  module Newest
    extend ActiveSupport::Concern

    # Returns users sorted by their creation date. Inheriting classes are
    # excluded.
    def newest: () -> untyped
  end
end
