class CreateHierarchicalItems < ActiveRecord::Migration[7.1]
  def change
    create_table :hierarchical_items do |t|
      t.integer :parent_id
      t.integer :sort_order
      t.string :label
      t.string :short
      t.boolean :is_deleted, default: false, null: false

      t.timestamps
    end

    add_reference "hierarchical_items", :custom_field, foreign_key: true

    # auto-generated by closure_tree
    create_table :hierarchical_item_hierarchies, id: false do |t|
      t.integer :ancestor_id, null: false
      t.integer :descendant_id, null: false
      t.integer :generations, null: false
    end

    add_index :hierarchical_item_hierarchies, %i[ancestor_id descendant_id generations],
              unique: true,
              name: "item_anc_desc_idx"

    add_index :hierarchical_item_hierarchies, [:descendant_id],
              name: "item_desc_idx"
  end
end
