class Activities::NewsActivityProvider < Activities::BaseActivityProvider
  def event_query_projection: () -> ::Array[untyped]

  def event_title: (untyped event) -> untyped

  def event_type: (untyped _event) -> "news"

  def event_path: (untyped event) -> untyped

  def event_url: (untyped event) -> untyped

  private

  def url_helper_parameter: (untyped event) -> untyped
end
