# frozen_string_literal: true

#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

require "English"
require "json"

module OpenProject
  module ApiDocCoverage
    # Files/updates one work package per endpoint module with hard gaps, via the
    # `op` CLI. The `runner` callable is injected so it can be stubbed in tests;
    # it receives the `op` argument vector and must return stdout, raising if the
    # command fails.
    class WpFiler
      DEFAULT_RUNNER = lambda do |args|
        stdout = IO.popen(["op", *args], &:read)
        raise "`op #{args.join(' ')}` failed (exit #{$CHILD_STATUS.exitstatus}): #{stdout}" unless $CHILD_STATUS.success?

        stdout
      end

      def initialize(report_hash:, ledger:, project:, runner: DEFAULT_RUNNER)
        @report = report_hash
        @ledger = ledger
        @project = project
        @runner = runner
      end

      def file(modules:)
        modules.filter_map { |mod| file_module(mod) }
      end

      private

      def file_module(mod)
        group = @report.dig("modules", mod)
        return nil if group.nil? || Array(group["undocumented_routes"]).empty?

        existing = @ledger.id_for(mod)
        existing ? update(mod, existing, group) : create(mod, group)
      end

      def create(mod, group)
        stdout = @runner.call(["work-package", "create", subject(mod),
                               "--project", @project, "--type", "TASK",
                               "--description", body(mod, group), "--format", "json"])
        wp_id = parse_id(stdout)
        @ledger.record(mod, wp_id) if wp_id
        { module: mod, wp_id:, action: :created }
      end

      def update(mod, wp_id, group)
        @runner.call(["work-package", "update", wp_id, "--description", body(mod, group)])
        { module: mod, wp_id:, action: :updated }
      end

      # `op ... --format json` prints the created work package as JSON; fall back
      # to scanning for "#<id>" in case a runner returns plain text.
      def parse_id(stdout)
        JSON.parse(stdout)["id"]&.to_s
      rescue JSON::ParserError
        stdout[/#(\d+)/, 1]
      end

      def subject(mod)
        "API docs: undocumented endpoints in #{mod}"
      end

      def body(mod, group)
        lines = ["Undocumented APIv3 routes for `#{mod}` (generated by rake api:docs:coverage):", ""]
        group["undocumented_routes"].each { |r| lines << "- `#{r}`" }
        unless Array(group["undocumented_params"]).empty?
          lines << "" << "Endpoints with undocumented params:"
          group["undocumented_params"].each { |h| lines << "- `#{h['endpoint']}` — #{h['params'].join(', ')}" }
        end
        lines.join("\n")
      end
    end
  end
end
