# Return alert mail notifications that are unread (have mail_alert_sent: false)
module Notifications::Scopes
  module MailAlertUnsent
    extend ActiveSupport::Concern

    def mail_alert_unsent: () -> untyped
  end
end
