# Return digest mail notifications that are unread (have read_digest_mail: false)
module Notifications::Scopes
  module MailReminderUnsent
    extend ActiveSupport::Concern

    def mail_reminder_unsent: () -> untyped
  end
end
