# frozen_string_literal: true

#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

require_relative "scanner"

def added_html_safe_files
  (git.modified_files + git.added_files)
    .reject { |file| HtmlSafeDangerScanner.skip_path?(file) }
    .select { |file| File.exist?(file) }
    .select { |file| added_non_empty_html_safe?(file) }
end

def added_non_empty_html_safe?(file)
  diff = git.diff_for_file(file)
  return false unless diff

  diff.patch.to_s.lines.any? { |line| HtmlSafeDangerScanner.added_non_empty_html_safe_line?(line) }
end

flagged_files = added_html_safe_files

if flagged_files.any?
  message_lines = [
    "@opf/security **New `.html_safe` usage found.** Please review for injection safety.",
    ""
  ]

  flagged_files.each do |file|
    message_lines << "- #{file}"
  end

  message_lines << <<~MESSAGE

    `.html_safe` marks a string as trusted HTML. Empty `"".html_safe` / `''.html_safe` buffers are ignored.

    Prefer `safe_join`, `content_tag`, `_html` I18n keys, or `sanitize` / `sanitize_basic_html` instead.
    If `.html_safe` is required, confirm the string is escaped or sanitized first.
  MESSAGE

  warn message_lines.join("\n")
end
