module API
  module V3
    module WorkPackages
      module Schema
        class TypedWorkPackageSchema < BaseWorkPackageSchema
          attr_reader project: untyped

          attr_reader type: untyped

          attr_reader custom_fields: untyped

          def initialize: (project: untyped, type: untyped, ?custom_fields: untyped?) -> void

          def milestone?: () -> untyped

          def available_custom_fields: () -> untyped

          def no_caching?: () -> false

          private

          def contract: () -> untyped

          def work_package: () -> untyped
        end
      end
    end
  end
end
