module API
  module V3
    module WorkPackages
      module Schema
        class WorkPackageSumsSchema < BaseWorkPackageSchema
          def available_custom_fields: () -> untyped

          def writable?: (untyped _property) -> false

          def work_package: () -> nil
        end
      end
    end
  end
end
