module Aws
  module Waiters
    module Errors
      class WaiterFailed < StandardError
      end
      class FailureStateError < WaiterFailed
      end
      class TooManyAttemptsError < WaiterFailed
      end
      class UnexpectedError < WaiterFailed
      end
      class NoSuchWaiterError < ArgumentError
      end
    end
  end
end
