module OpenProject::Backlogs::Patches::ProjectSeederPatch
  def self.included: (untyped base) -> untyped

  module InstanceMethods
    def seed_versions: () -> (nil | untyped)

    #
    # This relies on the names from the core's `config/locales/en.seeders.yml`.
    def version_settings_display_map: () -> ::Hash[::String, untyped]
  end
end
