module LdapGroups
  module SynchronizedFilters
    class TableComponent < ::TableComponent
      def initial_sort: () -> ::Array[:id | :asc]

      def target_controller: () -> "ldap_groups/synchronized_filters"

      def sortable?: () -> false

      def inline_create_link: () -> untyped

      def headers: () -> ::Array[::Array["name" | { caption: untyped }] | ::Array["auth_source" | { caption: untyped }] | ::Array["groups" | { caption: untyped }] | ::Array["sync_users" | { caption: untyped }]]
    end
  end
end
