class Users::ProjectAuthorizationCache
  attr_accessor user: untyped

  def initialize: (untyped user) -> void

  def cache: (untyped actions) -> untyped

  def cached?: (untyped action) -> untyped

  def allowed?: (untyped action, untyped project) -> untyped

  private

  def normalized_permission_name: (untyped action) -> untyped

  def projects_by_actions: () -> untyped
end
