#!/usr/bin/env bash
echo "ruby '2.1.6'" > Gemfile.local

cp -f packaging/conf/configuration.yml config/configuration.yml
sed -i "s|config.serve_static_assets = false|config.serve_static_assets = true|" config/environments/production.rb

cp -f packaging/conf/000-establish-connection.rb config/initializers/

# Specific npmrc used for packaging
cp -f packaging/.npmrc .npmrc

# replace every occurrence of _APP_NAME_ with the corresponding application name we're packaging
find packaging/ -type f -print0 | xargs -0 sed -i "s|_APP_NAME_|${APP_NAME}|"
