FORMAT: 1A

# OpenProject API v3

<!-- include(apiv3/introduction.apib) -->
<!-- include(apiv3/basic-objects.apib) -->
<!-- include(apiv3/group-objects.apib) -->

<!-- include(apiv3/endpoints/activities.apib) -->
<!-- include(apiv3/endpoints/attachments.apib) -->
<!-- include(apiv3/endpoints/categories.apib) -->
<!-- include(apiv3/endpoints/configuration.apib) -->
<!-- include(apiv3/endpoints/custom-options.apib) -->
<!-- include(apiv3/endpoints/forms.apib) -->
<!-- include(apiv3/endpoints/help_texts.apib) -->
<!-- include(apiv3/endpoints/principals.apib) -->
<!-- include(apiv3/endpoints/priorities.apib) -->
<!-- include(apiv3/endpoints/projects.apib) -->
<!-- include(apiv3/endpoints/queries.apib) -->
<!-- include(apiv3/endpoints/relations.apib) -->
<!-- include(apiv3/endpoints/render.apib) -->
<!-- include(apiv3/endpoints/revisions.apib) -->
<!-- include(apiv3/endpoints/roles.apib) -->
<!-- include(apiv3/endpoints/root.apib) -->
<!-- include(apiv3/endpoints/schemas.apib) -->
<!-- include(apiv3/endpoints/statuses.apib) -->
<!-- include(apiv3/endpoints/string-objects.apib) -->
<!-- include(apiv3/endpoints/types.apib) -->
<!-- include(apiv3/endpoints/user-preferences.apib) -->
<!-- include(apiv3/endpoints/users.apib) -->
<!-- include(apiv3/endpoints/versions.apib) -->
<!-- include(apiv3/endpoints/work-packages.apib) -->
