module API
  module V3
    module Grids
      class GridPayloadRepresenter < GridRepresenter
        include ::API::Utilities::PayloadRepresenter

        include ::API::V3::Attachments::AttachablePayloadRepresenterMixin

        def widget_representer_class: () -> untyped
      end
    end
  end
end
