module API
  module V3
    module WorkPackages
      class WorkPackagePayloadRepresenter < WorkPackageRepresenter
        include ::API::Utilities::PayloadRepresenter

        include ::API::V3::Attachments::AttachablePayloadRepresenterMixin

        def writable_attributes: () -> untyped

        def load_complete_model: (untyped model) -> untyped
      end
    end
  end
end
