module API
  module V3
    module WorkPackages
      class WorkPackageAggregationGroup < ::API::Decorators::AggregationGroup
        def initialize: (untyped group_key, untyped count, query: untyped, current_user: untyped, ?sums: untyped?) -> void

        def has_sums?: () -> untyped

        attr_reader sums: untyped

        def value: () -> (::String | untyped)
      end
    end
  end
end
