module API
  module V3
    module Attachments
      module AttachablePayloadRepresenterMixin
        extend ActiveSupport::Concern

        def writable_attributes: () -> untyped
      end
    end
  end
end
