module API
  module V3
    module Projects
      module Copy
        class CreateFormRepresenter < FormRepresenter
          include API::Decorators::CreateForm

          def form_url: () -> untyped

          def resource_url: () -> untyped
        end
      end
    end
  end
end
