module API
  module V3
    module Projects
      module Copy
        class ParseCopyParamsService < ::API::V3::ParseResourceParamsService
          private

          def parse_attributes: (untyped request_body) -> { target_project_params: untyped, attributes_only: true, only: untyped, send_notifications: untyped }
        end
      end
    end
  end
end
