name: Dangerfile

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - 'docs/**'
      - 'help/**'
      - 'packaging/**'
      - '.pkgr.yml'

jobs:
  danger:
    if: github.repository_owner == 'opf'
    runs-on: [ubuntu-latest]
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Setup danger
        run: |
          gem install danger
      - name: Run inconsistent translations check
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          danger --verbose
