name: "Docs"

on:
  pull_request:
    branches:
      - dev
      - release/*
    paths:
      - 'docs/**'
      - 'config/static_links.yml'

permissions:
  contents: read

jobs:
  docs-links-check:
    name: Check internal links in documentation
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1
        with:
          bundler-cache: true
      - run: bundle exec ./script/docs/check_links
  docs-readme-case-check:
    name: Check README.md case in documentation
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - run: script/docs/check_readme_case
  docs-readme-yaml-header-syntax-check:
    name: Check README.md YAML header syntax in documentation
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1
        with:
          bundler-cache: true
      - run: script/docs/check_readme_yaml_header_syntax
