name: "Hocuspocus / Dockerize"

on:
  # for continuous integration
  push:
    branches:
      - dev
      - release/*
    paths:
      - 'extensions/op-blocknote-hocuspocus/**'
      - '.github/workflows/hocuspocus-docker.yml'
  # for manually triggered builds
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch or tag to checkout and build"
        required: true
        type: string
      tag:
        description: "The main docker tag to use (e.g., 'dev' or '16.3.0')"
        required: true
        type: string
      use_test_registry:
        description: "Use openproject/hocuspocus-test registry instead (for testing)"
        required: false
        type: boolean
        default: false
  # for use within docker.yml
  workflow_call:
    inputs:
      branch:
        description: "The branch or tag to checkout and build"
        required: true
        type: string
      tag:
        description: "The main docker tag to use (e.g., 'dev' or '16.3.0')"
        required: true
        type: string
      # this option may be passed in from docker.yml if docker.yml was called with it as well
      use_test_registry:
        description: "Use openproject/hocuspocus-test registry instead (for testing)"
        required: false
        type: boolean
        default: false
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      DEPLOY_APP_PRIVATE_KEY:
        required: true

jobs:
  build:
    if: github.repository == 'opf/openproject'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ inputs.branch }} # this is empty on push, so it just checks out the event SHA in that case
          persist-credentials: false
      - name: Include Git SHA in package.json version
        id: short-sha
        run: |
          SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`

          # also include Git SHA in version string
          sed -ri "s/\"version\": \"(.*)\"/\"version\": \"\1-$SHORT_SHA\"/g" extensions/op-blocknote-hocuspocus/package.json

          echo "short_sha=$SHORT_SHA" >> "$GITHUB_OUTPUT"
      - name: Determine tags
        id: tags
        env:
          INPUT_USE_TEST_REGISTRY: ${{ inputs.use_test_registry }}
          INPUT_BRANCH: ${{ inputs.branch }}
          FALLBACK_BRANCH: ${{ github.ref_name }}
          INPUT_TAG: ${{ inputs.tag }}
          SHORT_SHA: ${{ steps.short-sha.outputs.short_sha }}
        run: |
          REGISTRY=openproject/hocuspocus

          if [ "$INPUT_USE_TEST_REGISTRY" = "true" ]; then
            REGISTRY=openproject/hocuspocus-test
          fi

          BRANCH=$(echo "${INPUT_BRANCH:-$FALLBACK_BRANCH}" | tr / -)
          SPECIFIC_TAG=$BRANCH-$SHORT_SHA
          LATEST_TAG=$BRANCH-latest
          MINOR_TAG=
          MAJOR_TAG=

          if [ -n "$INPUT_TAG" ]; then
            SPECIFIC_TAG=$(echo "$INPUT_TAG" | tr -d v)
            LATEST_TAG=latest
            MINOR_TAG=$(echo $SPECIFIC_TAG | cut -d. -f1-2)
            MAJOR_TAG=$(echo $SPECIFIC_TAG | cut -d. -f1)
          fi

          echo 'tags<<EOF' >> $GITHUB_OUTPUT
          echo $REGISTRY:$SPECIFIC_TAG >> $GITHUB_OUTPUT
          echo $REGISTRY:$LATEST_TAG >> $GITHUB_OUTPUT
          [ -n "$MINOR_TAG" ] && echo $REGISTRY:$MINOR_TAG >> $GITHUB_OUTPUT
          [ -n "$MAJOR_TAG" ] && echo $REGISTRY:$MAJOR_TAG >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      - name: Build and push
        id: build
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: extensions/op-blocknote-hocuspocus
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summarize build
        run: |
          echo "Built and pushed the following tags:" >> $GITHUB_STEP_SUMMARY
          echo "${STEPS_TAGS_OUTPUTS_TAGS}" >> $GITHUB_STEP_SUMMARY
        env:
          STEPS_TAGS_OUTPUTS_TAGS: ${{ steps.tags.outputs.tags }}

      - name: Generate GHA token
        id: generate-gha-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        with:
          app-id: ${{ vars.DEPLOY_APP_ID }}
          private-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
          owner: opf
          repositories: saas-deploy

      - name: Set inputs JSON
        id: build-inputs
        env:
          HOCUSPOCUS_IMAGE: ${{ steps.tags.outputs.tags }}
          THIS_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          # get the tag only from the first given image in "org/repository:tag1 org/repository:tag2"
          HOCUSPOCUS_TAG=$(echo $HOCUSPOCUS_IMAGE | cut -d' ' -f1 | cut -d':' -f2)

          inputs_json=$(jq -cn \
            --arg tag "$HOCUSPOCUS_TAG" \
            --arg url "$THIS_RUN_URL" \
            '{hocuspocus_image_tag: $tag, triggered_by_url: $url}')
          echo "inputs_json=$inputs_json" >> $GITHUB_OUTPUT

      - name: Deploy EDGE
        if: github.ref == 'refs/heads/dev' && github.repository == 'opf/openproject'
        uses: benc-uk/workflow-dispatch@31e2b3319479a63f0ab15bf800eff9e913504e26
        with:
          workflow: edge-deploy-shards.yml
          repo: opf/saas-deploy
          ref: master
          inputs: ${{ steps.build-inputs.outputs.inputs_json }}
          token: "${{ steps.generate-gha-token.outputs.token }}"

      - name: Deploy STAGE
        # make sure to always use the latest release branch here
        if: github.ref == 'refs/heads/release/17.6' && github.repository == 'opf/openproject'
        uses: benc-uk/workflow-dispatch@31e2b3319479a63f0ab15bf800eff9e913504e26
        with:
          workflow: stage-deploy-shards.yml
          repo: opf/saas-deploy
          ref: master
          inputs: ${{ steps.build-inputs.outputs.inputs_json }}
          token: "${{ steps.generate-gha-token.outputs.token }}"
