name: "Hocuspocus / Tests"
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'extensions/op-blocknote-hocuspocus/**'

permissions:
  contents: read

defaults:
  run:
    working-directory: ./extensions/op-blocknote-hocuspocus

jobs:
  units:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24.18.0'
          package-manager-cache: false
          cache: npm
          cache-dependency-path: extensions/op-blocknote-hocuspocus/package-lock.json

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: run tests
        id: npm-test
        run: CI=1 npm test
