name: i18n-inconsistency-check

on:
  push:
    branches:
      - dev
      - release/*
    paths-ignore:
      - "docs/**"
      - "help/**"
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - "docs/**"
      - "help/**"
      - "packaging/**"
      - ".pkgr.yml"

permissions:
  contents: read

jobs:
  i18n-tasks:
    permissions:
      contents: read
    if: github.repository == 'opf/openproject'
    name: I18n inconsistency check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1

      - name: Setup i18n-tasks
        run: |
          gem install i18n-tasks

      - name: Run inconsistent translations check
        run: |
          i18n-tasks \
            check-consistent-interpolations \
            --config config/i18n-tasks-all-files.yml
