name: "OpenAPI"
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests
on:
  push:
    branches:
      - dev
      - release/*
    paths:
      - 'docs/api/apiv3/**'
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'docs/api/apiv3/**'

jobs:
  api-spec:
    name: APIv3 specification (OpenAPI 3.0)
    if: github.repository_owner == 'opf'
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1
      with:
        bundler-cache: false
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: '24.18.0'
        package-manager-cache: false
    - run: ./script/api/validate_spec
