name: Package
on:
  push:
    tags:
      - v*
    branches:
      - packaging/*
      - release/*
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Daily at 03:00

jobs:
  build:
    if: github.repository == 'opf/openproject'
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: app
          POSTGRES_USER: app
          POSTGRES_PASSWORD: p4ssw0rd
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        target:
          - debian:11
          - debian:12
          - ubuntu:20.04
          - ubuntu:22.04
          - el:9
          - sles:15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup
        id: setup
        run: |
          VERSION=$(ruby -r ./lib/open_project/version.rb -e "puts OpenProject::VERSION")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            MAJOR=$(ruby -r ./lib/open_project/version.rb -e "puts OpenProject::VERSION::MAJOR")
            echo "channel=stable/${MAJOR}" >> $GITHUB_OUTPUT
          else
            echo "channel=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi
      - name: Package
        uses: pkgr/action/package@c5666febcd31750da6428042193fc5b2fb765435 # main
        id: package
        with:
          target: ${{ matrix.target }}
          version: ${{ steps.setup.outputs.version }}
          debug: true
          cache_prefix: ${{ github.ref_name }}
          env: |
            DATABASE_URL=postgres://app:p4ssw0rd@127.0.0.1:5432/app
      - name: Publish
        uses: pkgr/action/publish@c5666febcd31750da6428042193fc5b2fb765435 # main
        with:
          target: ${{ matrix.target }}
          token: ${{ secrets.PACKAGER_PUBLISH_TOKEN }}
          repository: opf/openproject
          channel: ${{ steps.setup.outputs.channel }}
          file: ${{ steps.package.outputs.package_path }}
