name: RuboCop

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1
      - name: Run RuboCop
        uses: reviewdog/action-rubocop@b6d5e953a5fc0bf3ab65254e77730ea2174d6d6d # v2
        with:
          reporter: github-pr-check
          rubocop_version: gemfile
          rubocop_extensions: >
            rubocop-capybara:gemfile
            rubocop-factory_bot:gemfile
            rubocop-openproject:gemfile
            rubocop-performance:gemfile
            rubocop-rails:gemfile
            rubocop-rspec:gemfile
            rubocop-rspec_rails:gemfile
          only_changed: true
