name: "Frontend test suite"

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - release/*
    paths:
      - '**/frontend/**/*.ts'
      - '**/frontend/**/*.js'
      - '**/frontend/**/*.json'

  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**/frontend/**/*.ts'
      - '**/frontend/**/*.js'
      - '**/frontend/**/*.json'

permissions:
  contents: read

defaults:
  run:
    working-directory: ./frontend

jobs:
  unit:
    name: Units (${{ matrix.browser }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '22.22.3'
          package-manager-cache: false

      - name: Install Dependencies
        run: npm ci

      - name: Register plugins
        run: npm run ci:plugins:register_frontend

      - name: Install Playwright dependencies
        timeout-minutes: 5
        run: npx playwright install-deps ${{ matrix.browser }}

      - name: Install Playwright Browser
        timeout-minutes: 5
        run: npx playwright install --only-shell ${{ matrix.browser }}

      - name: Test
        run: npm test -- --browsers ${{ matrix.browser }} --reporters dot --reporters github-actions
