name: Check work package version

on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize
      - ready_for_review

permissions:
  contents: read # to fetch code (actions/checkout)
  pull-requests: write  # to comment on the PR

jobs:
  version-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1

      - name: Verify linked version matches core version
        id: version-check
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: ./script/ci/version_check.sh

      - name: Add comment if no work package is linked
        if: steps.version-check.outputs.no_ticket == 'true'
        uses: marocchino/sticky-pull-request-comment@d4d6b0936434b21bc8345ad45a440c5f7d2c40ff # v3
        with:
          header: version-mismatch-comment
          message: |
            > [!WARNING]
            > This pull request does not link an OpenProject work package.

            Please add a link to the work package in the description, or reference it in the
            title in square brackets, e.g. `[SLUG-123] My title here`.

      - name: Add comment if versions differ
        if: steps.version-check.outputs.version_mismatch == 'true'
        uses: marocchino/sticky-pull-request-comment@d4d6b0936434b21bc8345ad45a440c5f7d2c40ff # v3
        with:
          header: version-mismatch-comment
          message: |
            > [!CAUTION]
            > The provided work package version does not match the core version

            Details:

             - Work package URL: ${{ steps.version-check.outputs.wp_url }}
             - Work package version: ${{steps.version-check.outputs.wp_version}}
             - Core version: ${{steps.version-check.outputs.core_version}}

            Please make sure that:

             - The work package version OR your pull request target branch is correct
      - name: Version check passed
        if: steps.version-check.outputs.version_mismatch != 'true' && steps.version-check.outputs.no_ticket != 'true'
        uses: marocchino/sticky-pull-request-comment@d4d6b0936434b21bc8345ad45a440c5f7d2c40ff # v3
        with:
          header: version-mismatch-comment
          delete: true
