name: Yamllint

on:
  pull_request:
    paths:
      - '.yamllint.yml'
      - 'config/locales/en.yml'
      - 'config/locales/js-en.yml'
      - 'modules/*/config/locales/en.yml'
      - 'modules/*/config/locales/js-en.yml'

jobs:
  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Yamllint
        uses: reviewdog/action-yamllint@de68272fdca5f2a961fb309e0d2e13c2eb186d9e # v1.23.1
        with:
          reporter: github-pr-annotations
          fail_level: any
          yamllint_flags: >
            .yamllint.yml
            config/locales/en.yml
            config/locales/js-en.yml
            modules/*/config/locales/en.yml
            modules/*/config/locales/js-en.yml
