name: GitHub Actions Security Analysis with zizmor 🌈

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    if: github.repository_owner == 'opf'
    permissions:
      security-events: write # Required for upload-sarif
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99 # v0.6.3
