module Notifications
  class SetAttributesService < ::BaseServices::SetAttributes
    private

    def set_default_attributes: (untyped params) -> untyped

    #
    # Try to determine the project context from the journal (if any)
    # or the resource if it has a project set
    def set_default_project: () -> untyped
  end
end
