module OpenProject
  #
  # Provides helpers from ActiveRecord::Sanitization
  # outside model context
  module SqlSanitization
    include ::ActiveRecord::Sanitization

    def self.connection: () -> untyped

    #
    # Shorthand for:
    # sanitize_sql_array [str, :param0, param1]
    # sanitize_sql_array [str, param0: foo, param1: bar]
    def self.sanitize: (untyped sql, *untyped args) -> untyped
  end
end
