module OpenProject
  module VERSION
    MAJOR: 13

    MINOR: 0

    PATCH: 0

    # Used by semver to define the special version (if any).
    # A special version "satisfy but have a lower precedence than the associated
    # normal version". So 2.0.0RC1 would be part of the 2.0.0 series but
    # be considered to be an older version.
    #
    #   1.4.0 < 2.0.0RC1 < 2.0.0RC2 < 2.0.0 < 2.1.0
    #
    # This method may be overridden by third party code to provide vendor or
    # distribution specific versions. They may or may not follow semver.org:
    #
    #   2.0.0debian-2
    def self.special: () -> ""

    def self.revision: () -> untyped

    def self.product_version: () -> untyped

    def self.core_version: () -> untyped

    #
    # Get information on when this version was created / updated from either
    # 1. A RELEASE_DATE file
    # 2. From the git revision
    def self.updated_on: () -> untyped

    def self.to_a: () -> untyped

    def self.to_s: () -> untyped

    def self.to_semver: () -> untyped

    private

    def self.release_date_from_file: () -> untyped

    def self.release_date_from_git: () -> untyped

    def self.revision_from_core_version: () -> (nil | untyped)

    def self.revision_from_git: () -> untyped

    def self.cached_or_block: (untyped variable) { () -> untyped } -> untyped

    public

    REVISION: untyped

    ARRAY: untyped

    STRING: untyped
  end
end
